version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/packages/design_builder_flutter"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      prefix-development: "chore(dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "pub"
    groups:
      production-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
