import 'package:design_builder/src/generators/theme_generator.dart';
import 'package:design_builder/src/models/design_token.dart';
import 'package:design_builder/src/models/theme_config.dart';
import 'package:design_builder/src/models/token_group.dart';
import 'package:test/test.dart';

void main() {
  group('ThemeGenerator', () {
    late ThemeConfig config;
    late ThemeGenerator generator;

    setUp(() {
      config = ThemeConfig(
        className: 'TestTheme',
        outputPath: 'test_output',
        outputFileName: 'test_theme',
      );
      generator = ThemeGenerator(config);
    });

    group('generateUnified', () {
      test('generates file header', () {
        final modeGroups = <String, List<TokenGroup>>{};
        final modeTokens = <String, List<DesignToken>>{};
        final modes = <String>['light'];
        final groupDescriptions = <String, String>{};

        final code = generator.generateUnified(
          modeGroups,
          modeTokens,
          modes,
          groupDescriptions,
          'Test theme description',
        );

        expect(code, contains('// GENERATED CODE - DO NOT MODIFY MANUALLY'));
        expect(code, contains('Generated by design_builder'));
        expect(code, contains('Test theme description'));
        expect(code, contains("import 'package:flutter/material.dart';"));
      });

      test('generates AppTheme class', () {
        final modeGroups = <String, List<TokenGroup>>{};
        final modeTokens = <String, List<DesignToken>>{};
        final modes = <String>['light'];
        final groupDescriptions = <String, String>{};

        final code = generator.generateUnified(
          modeGroups,
          modeTokens,
          modes,
          groupDescriptions,
          null,
        );

        expect(
          code,
          contains('class TestTheme extends ThemeExtension<TestTheme>'),
        );
        expect(code, contains('factory TestTheme.dark()'));
        expect(code, contains('factory TestTheme.light()'));
        expect(code, contains('static TestTheme of(BuildContext context)'));
      });

      test('generates mode enum', () {
        final modeGroups = <String, List<TokenGroup>>{};
        final modeTokens = <String, List<DesignToken>>{};
        final modes = <String>['light', 'dark'];
        final groupDescriptions = <String, String>{};

        final code = generator.generateUnified(
          modeGroups,
          modeTokens,
          modes,
          groupDescriptions,
          null,
        );

        expect(code, contains('enum TestThemeMode'));
        expect(code, contains('light, dark'));
      });

      test('generates _TokenStore class', () {
        final modeGroups = <String, List<TokenGroup>>{};
        final modeTokens = <String, List<DesignToken>>{};
        final modes = <String>['light'];
        final groupDescriptions = <String, String>{};

        final code = generator.generateUnified(
          modeGroups,
          modeTokens,
          modes,
          groupDescriptions,
          null,
        );

        expect(code, contains('class _TokenStore'));
        expect(code, contains('Color? color'));
        expect(code, contains('double? size'));
        expect(code, contains('TextStyle? textStyle'));
      });

      test('generates theme provider classes', () {
        final modeGroups = <String, List<TokenGroup>>{};
        final modeTokens = <String, List<DesignToken>>{};
        final modes = <String>['light', 'dark'];
        final groupDescriptions = <String, String>{};

        final code = generator.generateUnified(
          modeGroups,
          modeTokens,
          modes,
          groupDescriptions,
          null,
        );

        expect(
          code,
          contains('class TestThemeNotifier extends ChangeNotifier'),
        );
        expect(
          code,
          contains('class TestThemeProvider extends InheritedNotifier'),
        );
        expect(code, contains('toggleMode'));
        expect(code, contains('applyOverrides'));
        expect(code, contains('clearOverrides'));
      });

      test('generates context extensions', () {
        final modeGroups = <String, List<TokenGroup>>{};
        final modeTokens = <String, List<DesignToken>>{};
        final modes = <String>['light'];
        final groupDescriptions = <String, String>{};

        final code = generator.generateUnified(
          modeGroups,
          modeTokens,
          modes,
          groupDescriptions,
          null,
        );

        expect(
          code,
          contains('extension TestThemeContextExtensions on BuildContext'),
        );
        expect(code, contains('TestTheme get theme'));
        expect(code, contains('TestThemeNotifier get themeNotifier'));
      });
    });

    group('with color tokens', () {
      test('generates color lookup map', () {
        final token = DesignToken(
          path: 'light.color.brand.primary',
          type: 'color',
          value: '#FF0000',
          raw: {'\$type': 'color', '\$value': '#FF0000'},
        );

        final group = TokenGroup(
          name: 'brand',
          category: 'color',
          tokenPaths: ['light.color.brand.primary'],
          tokens: [token],
        );

        final modeGroups = {
          'light': [group],
        };
        final modeTokens = {
          'light': [token],
        };
        final modes = ['light'];
        final groupDescriptions = <String, String>{};

        final code = generator.generateUnified(
          modeGroups,
          modeTokens,
          modes,
          groupDescriptions,
          null,
        );

        expect(code, contains('const Map<String, Color> _lightColorBrand'));
        expect(code, contains('Color(0xFFFF0000)'));
      });

      test('generates color resolver class', () {
        final token = DesignToken(
          path: 'light.color.brand.primary',
          type: 'color',
          value: '#FF0000',
          raw: {'\$type': 'color', '\$value': '#FF0000'},
        );

        final group = TokenGroup(
          name: 'brand',
          category: 'color',
          tokenPaths: ['light.color.brand.primary'],
          tokens: [token],
        );

        final modeGroups = {
          'light': [group],
        };
        final modeTokens = {
          'light': [token],
        };
        final modes = ['light'];
        final groupDescriptions = <String, String>{};

        final code = generator.generateUnified(
          modeGroups,
          modeTokens,
          modes,
          groupDescriptions,
          null,
        );

        expect(code, contains('class _BrandColors'));
        expect(code, contains('Color get primary'));
      });
    });

    group('with size tokens', () {
      test('generates size lookup map', () {
        final token = DesignToken(
          path: 'light.sizes.padding.md',
          type: 'dimension',
          value: 16,
          raw: {'\$type': 'dimension', '\$value': 16},
        );

        final group = TokenGroup(
          name: 'padding',
          category: 'sizes',
          tokenPaths: ['light.sizes.padding.md'],
          tokens: [token],
        );

        final modeGroups = {
          'light': [group],
        };
        final modeTokens = {
          'light': [token],
        };
        final modes = ['light'];
        final groupDescriptions = <String, String>{};

        final code = generator.generateUnified(
          modeGroups,
          modeTokens,
          modes,
          groupDescriptions,
          null,
        );

        expect(code, contains('const Map<String, double> _lightSizePadding'));
        expect(code, contains("'md': 16.0"));
      });

      test('generates size resolver class', () {
        final token = DesignToken(
          path: 'light.sizes.padding.md',
          type: 'dimension',
          value: 16,
          raw: {'\$type': 'dimension', '\$value': 16},
        );

        final group = TokenGroup(
          name: 'padding',
          category: 'sizes',
          tokenPaths: ['light.sizes.padding.md'],
          tokens: [token],
        );

        final modeGroups = {
          'light': [group],
        };
        final modeTokens = {
          'light': [token],
        };
        final modes = ['light'];
        final groupDescriptions = <String, String>{};

        final code = generator.generateUnified(
          modeGroups,
          modeTokens,
          modes,
          groupDescriptions,
          null,
        );

        expect(code, contains('class _PaddingSizes'));
        expect(code, contains('double get md'));
      });
    });

    group('with typography tokens', () {
      test('generates typography lookup map', () {
        final token = DesignToken(
          path: 'light.typography.body.regular',
          type: 'typography',
          value: {'fontSize': 16, 'fontWeight': 400},
          raw: {
            '\$type': 'typography',
            '\$value': {'fontSize': 16, 'fontWeight': 400},
          },
        );

        final group = TokenGroup(
          name: 'body',
          category: 'typography',
          tokenPaths: ['light.typography.body.regular'],
          tokens: [token],
        );

        final modeGroups = {
          'light': [group],
        };
        final modeTokens = {
          'light': [token],
        };
        final modes = ['light'];
        final groupDescriptions = <String, String>{};

        final code = generator.generateUnified(
          modeGroups,
          modeTokens,
          modes,
          groupDescriptions,
          null,
        );

        expect(
          code,
          contains('const Map<String, TextStyle> _lightTypographyBody'),
        );
        expect(
          code,
          contains('TextStyle(fontSize: 16, fontWeight: FontWeight.w400)'),
        );
      });

      test('generates typography resolver class', () {
        final token = DesignToken(
          path: 'light.typography.body.regular',
          type: 'typography',
          value: {'fontSize': 16, 'fontWeight': 400},
          raw: {
            '\$type': 'typography',
            '\$value': {'fontSize': 16, 'fontWeight': 400},
          },
        );

        final group = TokenGroup(
          name: 'body',
          category: 'typography',
          tokenPaths: ['light.typography.body.regular'],
          tokens: [token],
        );

        final modeGroups = {
          'light': [group],
        };
        final modeTokens = {
          'light': [token],
        };
        final modes = ['light'];
        final groupDescriptions = <String, String>{};

        final code = generator.generateUnified(
          modeGroups,
          modeTokens,
          modes,
          groupDescriptions,
          null,
        );

        expect(code, contains('class _BodyTypography'));
        expect(code, contains('TextStyle get regular'));
      });
    });

    group('with multiple modes', () {
      test('generates maps for both light and dark modes', () {
        final lightToken = DesignToken(
          path: 'light.color.brand.primary',
          type: 'color',
          value: '#FF0000',
          raw: {'\$type': 'color', '\$value': '#FF0000'},
        );

        final darkToken = DesignToken(
          path: 'dark.color.brand.primary',
          type: 'color',
          value: '#00FF00',
          raw: {'\$type': 'color', '\$value': '#00FF00'},
        );

        final group = TokenGroup(
          name: 'brand',
          category: 'color',
          tokenPaths: ['light.color.brand.primary', 'dark.color.brand.primary'],
        );

        final modeGroups = {
          'light': [group],
          'dark': [group],
        };
        final modeTokens = {
          'light': [lightToken],
          'dark': [darkToken],
        };
        final modes = ['light', 'dark'];
        final groupDescriptions = <String, String>{};

        final code = generator.generateUnified(
          modeGroups,
          modeTokens,
          modes,
          groupDescriptions,
          null,
        );

        expect(code, contains('_lightColorBrand'));
        expect(code, contains('_darkColorBrand'));
        expect(code, contains('Color(0xFFFF0000)'));
        expect(code, contains('Color(0xFF00FF00)'));
      });
    });

    group('with nested groups', () {
      test('generates nested typography structure', () {
        final token = DesignToken(
          path: 'light.typography.display.h1.bold',
          type: 'typography',
          value: {'fontSize': 48, 'fontWeight': 700},
          raw: {
            '\$type': 'typography',
            '\$value': {'fontSize': 48, 'fontWeight': 700},
          },
        );

        final h1Group = TokenGroup(
          name: 'h1',
          category: 'typography',
          tokenPaths: ['light.typography.display.h1.bold'],
          tokens: [token],
        );

        final displayGroup = TokenGroup(
          name: 'display',
          category: 'typography',
          children: [h1Group],
        );

        final modeGroups = {
          'light': [displayGroup],
        };
        final modeTokens = {
          'light': [token],
        };
        final modes = ['light'];
        final groupDescriptions = <String, String>{};

        final code = generator.generateUnified(
          modeGroups,
          modeTokens,
          modes,
          groupDescriptions,
          null,
        );

        // The generator creates class names based on the full path
        // For display.h1, it should create _DisplayH1Typography
        expect(code, contains('_ThemeTypography')); // Helper class is generated
        expect(
          code,
          contains('_DisplayTypography'),
        ); // Display typography class
        // The generated code may vary based on the tree structure
        // We verify the code was generated successfully
        expect(code, isNotEmpty);
        expect(code, contains('class TestTheme'));
      });
    });

    group('with group descriptions', () {
      test('includes group descriptions in comments', () {
        final token = DesignToken(
          path: 'light.color.brand.primary',
          type: 'color',
          value: '#FF0000',
          raw: {'\$type': 'color', '\$value': '#FF0000'},
        );

        final group = TokenGroup(
          name: 'brand',
          category: 'color',
          tokenPaths: ['light.color.brand.primary'],
          tokens: [token],
        );

        final modeGroups = {
          'light': [group],
        };
        final modeTokens = {
          'light': [token],
        };
        final modes = ['light'];
        final groupDescriptions = {
          'light.color.brand': 'Brand colors for the application',
        };

        final code = generator.generateUnified(
          modeGroups,
          modeTokens,
          modes,
          groupDescriptions,
          null,
        );

        expect(code, contains('Brand colors for the application'));
      });
    });

    group('edge cases', () {
      test('handles empty mode groups', () {
        final modeGroups = <String, List<TokenGroup>>{'light': []};
        final modeTokens = <String, List<DesignToken>>{'light': []};
        final modes = ['light'];
        final groupDescriptions = <String, String>{};

        final code = generator.generateUnified(
          modeGroups,
          modeTokens,
          modes,
          groupDescriptions,
          null,
        );

        expect(code, contains('class TestTheme'));
        expect(code, isNotEmpty);
      });

      test('handles token with empty value', () {
        final token = DesignToken(
          path: 'light.color.brand.primary',
          type: 'color',
          value: '',
          raw: {'\$type': 'color', '\$value': ''},
        );

        final group = TokenGroup(
          name: 'brand',
          category: 'color',
          tokenPaths: ['light.color.brand.primary'],
          tokens: [token],
        );

        final modeGroups = {
          'light': [group],
        };
        final modeTokens = {
          'light': [token],
        };
        final modes = ['light'];
        final groupDescriptions = <String, String>{};

        final code = generator.generateUnified(
          modeGroups,
          modeTokens,
          modes,
          groupDescriptions,
          null,
        );

        // Should generate without crashing, even if color parsing fails
        expect(code, contains('class TestTheme'));
      });
    });
  });
}
