import 'package:design_builder/src/models/design_token.dart';
import 'package:design_builder/src/models/theme_config.dart';
import 'package:design_builder/src/models/token_group.dart';
import 'package:design_builder/src/models/token_group_node.dart';
import 'package:design_builder/src/parsers/token_parser.dart';

/// Generates the AppTheme Dart code from design tokens.
///
/// This generator produces a unified theme file that supports multiple modes
/// (e.g., light/dark) with server-side override capabilities. The output
/// prioritizes developer experience by placing all class definitions first,
/// followed by const lookup maps at the end of the file.
///
/// Features:
/// - Const lookup maps for O(1) token resolution.
/// - Mode-aware unified lookup methods in _TokenStore.
/// - Server override support for dynamic theming.
/// - Non-nullable getters with fallback values.
/// - Recursive nesting support for arbitrary token depths.
class ThemeGenerator {
  ThemeGenerator(this.config);
  final ThemeConfig config;

  /// Map of group paths to their descriptions from the token file
  Map<String, String> _groupDescriptions = {};

  /// Primary mode (first mode in the list, used for lookups)
  String _primaryMode = 'light';

  /// Generates the complete Dart source file for the theme.
  ///
  /// The generated file is structured as follows:
  /// 1. File header and imports.
  /// 2. Main [AppTheme] class.
  /// 3. [AppThemeProvider] for state management.
  /// 4. [_TokenStore] for token lookup and overrides.
  /// 5. [BuildContext] extension for easy access.
  /// 6. Theme helper classes (_ThemeColors, _ThemeSizes, _ThemeTypography).
  /// 7. Category resolver classes (e.g., _BrandColors, _FontSizes, _DisplayTypography).
  /// 8. Const lookup maps (placed at the bottom for readability).
  ///
  /// Parameters:
  /// - [modeGroups]: Token groups organized by mode.
  /// - [modeTokens]: Design tokens organized by mode.
  /// - [modes]: List of supported mode names (e.g., ['dark', 'light']).
  /// - [groupDescriptions]: Map of group paths to their descriptions.
  /// - [rootDescription]: Root-level description from the token file.
  String generateUnified(
    Map<String, List<TokenGroup>> modeGroups,
    Map<String, List<DesignToken>> modeTokens,
    List<String> modes,
    Map<String, String> groupDescriptions,
    String? rootDescription,
  ) {
    _groupDescriptions = groupDescriptions;
    _primaryMode = modes.first;
    final buffer = StringBuffer();
    final primaryMode = modes.first;

    // Build a hierarchical tree structure from the flat groups
    final colorTree = _buildCategoryTree(
      modeGroups[primaryMode] ?? [],
      'color',
    );
    final sizeTree = _buildCategoryTree(modeGroups[primaryMode] ?? [], 'sizes');
    final typographyTree = _buildCategoryTree(
      modeGroups[primaryMode] ?? [],
      'typography',
    );

    // --- File Header ---
    buffer.writeln('// GENERATED CODE - DO NOT MODIFY MANUALLY');
    buffer.writeln('// Generated by design_builder');
    if (rootDescription != null && rootDescription.isNotEmpty) {
      buffer.writeln('//');
      final wrappedLines = _wrapText(rootDescription, maxWidth: 78, prefix: '// ');
      for (final line in wrappedLines) {
        buffer.writeln(line);
      }
    }
    buffer.writeln('//');
    buffer.writeln(
      '// This file contains theme configuration generated from design tokens.',
    );
    buffer.writeln('// To update, modify the source token files and rebuild.');
    buffer.writeln('//');
    buffer.writeln('// ignore_for_file: library_private_types_in_public_api, unnecessary_getters_setters');
    buffer.writeln();
    buffer.writeln("import 'package:flutter/material.dart';");
    buffer.writeln();

    // --- Main Theme Classes ---
    buffer.writeln(_generateAppTheme(colorTree, sizeTree, typographyTree));
    buffer.writeln();

    buffer.writeln(_generateThemeProvider(modes));
    buffer.writeln();

    buffer.writeln(
      _generateTokenStore(modes, colorTree, sizeTree, typographyTree),
    );
    buffer.writeln();

    buffer.writeln(_generateContextExtensions());
    buffer.writeln();

    // --- Helper and Resolver Classes ---
    buffer.writeln(
      _generateThemeHelperClasses(colorTree, sizeTree, typographyTree),
    );
    buffer.writeln();

    // Generate color resolver classes recursively.
    for (final node in colorTree) {
      buffer.writeln(_generateColorResolvers(node, modes, modeTokens));
    }
    if (colorTree.isNotEmpty) buffer.writeln();

    // Generate size resolver classes recursively.
    for (final node in sizeTree) {
      buffer.writeln(_generateSizeResolvers(node, modes, modeTokens));
    }
    if (sizeTree.isNotEmpty) buffer.writeln();

    // Generate typography resolver classes recursively.
    for (final node in typographyTree) {
      buffer.writeln(_generateTypographyResolvers(node, modes, modeTokens));
    }
    if (typographyTree.isNotEmpty) buffer.writeln();

    // --- Const Data (placed at the end for readability) ---
    // These maps contain the raw token values and are referenced by the
    // resolver classes above. Placing them at the bottom keeps the
    // API surface (classes) visible first when opening the file.
    buffer.writeln(
      _generateLookupMaps(
        modes,
        modeTokens,
        colorTree,
        sizeTree,
        typographyTree,
      ),
    );

    return buffer.toString();
  }

  /// Build a hierarchical tree from flat groups for a specific category.
  /// This organizes groups by their parent-child relationships.
  List<TokenGroupNode> _buildCategoryTree(
    List<TokenGroup> groups,
    String category,
  ) {
    final categoryGroups = groups
        .where((g) => g.category.toLowerCase() == category.toLowerCase())
        .toList();

    // Build tree structure
    final rootNodes = <TokenGroupNode>[];
    final nodeMap = <String, TokenGroupNode>{};

    // First pass: create all nodes
    for (final group in categoryGroups) {
      final fullPath = group.fullGroupPath;
      final node = TokenGroupNode(
        name: group.name,
        fullPath: fullPath,
        group: group,
        children: [],
      );
      nodeMap[fullPath] = node;
    }

    // Second pass: establish parent-child relationships
    for (final group in categoryGroups) {
      final fullPath = group.fullGroupPath;
      final node = nodeMap[fullPath]!;

      // Check if this is a root node or has a parent
      if (!group.isNested) {
        rootNodes.add(node);
      } else {
        // Find parent
        final parentPath = group.parent!.fullGroupPath;
        final parentNode = nodeMap[parentPath];
        if (parentNode != null) {
          parentNode.children.add(node);
        }
      }
    }

    // Sort root nodes for consistent output
    rootNodes.sort((a, b) => a.name.compareTo(b.name));

    return rootNodes;
  }

  /// Generates the const lookup maps containing raw token values.
  ///
  /// Creates one map per category group per mode:
  /// - `_{mode}Color{GroupName}` for colors.
  /// - `_{mode}Size{GroupName}` for dimensions.
  /// - `_{mode}Typography{GroupName}` for text styles.
  String _generateLookupMaps(
    List<String> modes,
    Map<String, List<DesignToken>> modeTokens,
    List<TokenGroupNode> colorTree,
    List<TokenGroupNode> sizeTree,
    List<TokenGroupNode> typographyTree,
  ) {
    final buffer = StringBuffer();

    for (final mode in modes) {
      final tokens = modeTokens[mode] ?? [];

      // Generate color maps recursively.
      for (final node in colorTree) {
        _generateColorMapsRecursive(buffer, mode, node, tokens);
      }

      // Generate size maps recursively.
      for (final node in sizeTree) {
        _generateSizeMapsRecursive(buffer, mode, node, tokens);
      }

      // Generate typography maps recursively.
      for (final node in typographyTree) {
        _generateTypographyMapsRecursive(buffer, mode, node, tokens);
      }
    }

    return buffer.toString();
  }

  void _generateColorMapsRecursive(
    StringBuffer buffer,
    String mode,
    TokenGroupNode node,
    List<DesignToken> tokens,
  ) {
    // Get all tokens that belong to this node (including from descendants)
    // Compare paths without mode prefix for cross-mode matching
    final allPaths = _getAllTokenPaths(
      node,
    ).map((p) => _stripModePrefix(p)).toList();
    final groupTokens = tokens
        .where((t) => allPaths.any((p) => _stripModePrefix(t.path) == p))
        .toList();

    if (groupTokens.isNotEmpty) {
      final mapName = '_${mode}Color${_pascalCasePath(node.fullPath)}';
      buffer.writeln();
      buffer.writeln('const Map<String, Color> $mapName = <String, Color>{');
      for (final t in groupTokens) {
        final tokenName = t.path.split('.').last;
        final colorVal = TokenParser.parseColor(t.value);
        if (colorVal != null) {
          buffer.writeln(
            "  '$tokenName': Color(0x${colorVal.toRadixString(16).padLeft(8, '0').toUpperCase()}),",
          );
        }
      }
      buffer.writeln('};');
    }

    // Recurse into children
    for (final child in node.children) {
      _generateColorMapsRecursive(buffer, mode, child, tokens);
    }
  }

  void _generateSizeMapsRecursive(
    StringBuffer buffer,
    String mode,
    TokenGroupNode node,
    List<DesignToken> tokens,
  ) {
    // Compare paths without mode prefix for cross-mode matching
    final allPaths = _getAllTokenPaths(
      node,
    ).map((p) => _stripModePrefix(p)).toList();
    final groupTokens = tokens
        .where((t) => allPaths.any((p) => _stripModePrefix(t.path) == p))
        .toList();

    if (groupTokens.isNotEmpty) {
      final mapName = '_${mode}Size${_pascalCasePath(node.fullPath)}';
      buffer.writeln();
      buffer.writeln('const Map<String, double> $mapName = <String, double>{');
      for (final t in groupTokens) {
        final tokenName = t.path.split('.').last;
        final numValue = t.value is num
            ? (t.value as num).toDouble()
            : (t.value is String
                  ? double.tryParse(
                      (t.value as String).replaceAll(
                        RegExp(r'(px|rem|em)$'),
                        '',
                      ),
                    )
                  : null);
        if (numValue != null) {
          buffer.writeln("  '$tokenName': $numValue,");
        }
      }
      buffer.writeln('};');
    }

    for (final child in node.children) {
      _generateSizeMapsRecursive(buffer, mode, child, tokens);
    }
  }

  void _generateTypographyMapsRecursive(
    StringBuffer buffer,
    String mode,
    TokenGroupNode node,
    List<DesignToken> tokens,
  ) {
    // Only generate maps for leaf nodes (groups with actual tokens)
    if (node.group.tokenPaths.isNotEmpty) {
      final mapName = '_${mode}Typography${_pascalCasePath(node.fullPath)}';
      // Compare paths without mode prefix for cross-mode matching
      final groupPaths = node.group.tokenPaths
          .map((p) => _stripModePrefix(p))
          .toList();
      final groupTokens = tokens
          .where((t) => groupPaths.contains(_stripModePrefix(t.path)))
          .toList();

      if (groupTokens.isNotEmpty) {
        buffer.writeln();
        buffer.writeln(
          'const Map<String, TextStyle> $mapName = <String, TextStyle>{',
        );
        for (final t in groupTokens) {
          final tokenName = t.path.split('.').last;
          final textStyle = _generateTextStyle(t.value);
          if (textStyle != null) {
            buffer.writeln("  '$tokenName': $textStyle,");
          }
        }
        buffer.writeln('};');
      }
    }

    // Recurse into children
    for (final child in node.children) {
      _generateTypographyMapsRecursive(buffer, mode, child, tokens);
    }
  }

  List<String> _getAllTokenPaths(TokenGroupNode node) {
    final result = <String>[...node.group.tokenPaths];
    for (final child in node.children) {
      result.addAll(_getAllTokenPaths(child));
    }
    return result;
  }

  /// Generates the _TokenStore class for managing theme tokens and overrides.
  ///
  /// This class provides the core lookup logic:
  /// - Checks server overrides first.
  /// - Falls back to const maps based on current mode.
  /// - Supports colors, sizes, and typography.
  String _generateTokenStore(
    List<String> modes,
    List<TokenGroupNode> colorTree,
    List<TokenGroupNode> sizeTree,
    List<TokenGroupNode> typographyTree,
  ) {
    final buffer = StringBuffer();

    buffer.writeln(
      '/// Manages theme token storage and server-side overrides.',
    );
    buffer.writeln('///');
    buffer.writeln(
      '/// The store maintains a current mode (e.g., "dark", "light") and a map',
    );
    buffer.writeln(
      '/// of overrides. All lookups check overrides first, then fall back',
    );
    buffer.writeln('/// to the const lookup maps for the current mode.');
    buffer.writeln('class _TokenStore {');
    buffer.writeln('  String _mode;');
    buffer.writeln('  Map<String, dynamic> _overrides = const {};');
    buffer.writeln();
    buffer.writeln('  _TokenStore({required String mode}) : _mode = mode;');
    buffer.writeln();
    buffer.writeln('  String get mode => _mode;');
    buffer.writeln('  set mode(String value) => _mode = value;');
    buffer.writeln();
    buffer.writeln('  Map<String, dynamic> get overrides => _overrides;');
    buffer.writeln();
    buffer.writeln('  void setOverrides(Map<String, dynamic> overrides) {');
    buffer.writeln('    _overrides = Map.unmodifiable(overrides);');
    buffer.writeln('  }');
    buffer.writeln();
    buffer.writeln('  void clearOverrides() {');
    buffer.writeln('    _overrides = const {};');
    buffer.writeln('  }');
    buffer.writeln();

    // Generate color lookup method with nested group support.
    buffer.writeln('  /// Looks up a color by full group path and token name.');
    buffer.writeln('  ///');
    buffer.writeln(
      '  /// Returns the override if one exists for the full path, otherwise',
    );
    buffer.writeln(
      '  /// returns the value from the const map for the current mode.',
    );
    buffer.writeln('  Color? color(String groupPath, String token) {');
    buffer.writeln('    // Check override first using the full token path.');
    buffer.writeln('    final path = "\$_mode.color.\$groupPath.\$token";');
    buffer.writeln('    final override = _overrides[path];');
    buffer.writeln('    if (override is Color) return override;');
    buffer.writeln();
    buffer.writeln('    // Lookup in the appropriate mode map.');
    buffer.writeln(
      r"    final pascalPath = groupPath.split('.').map((s) => _pascalCase(s)).join();",
    );
    buffer.writeln("    if (_mode == 'dark') {");
    buffer.writeln('      switch (pascalPath) {');
    _generateColorCaseStatements(buffer, colorTree, 'dark');
    buffer.writeln('      }');
    buffer.writeln('    } else {');
    buffer.writeln('      switch (pascalPath) {');
    _generateColorCaseStatements(buffer, colorTree, 'light');
    buffer.writeln('      }');
    buffer.writeln('    }');
    buffer.writeln('    return null;');
    buffer.writeln('  }');
    buffer.writeln();

    // Generate size lookup method.
    buffer.writeln(
      '  /// Looks up a size dimension by full group path and token name.',
    );
    buffer.writeln('  ///');
    buffer.writeln(
      '  /// Returns the override if one exists, otherwise returns the value',
    );
    buffer.writeln('  /// from the const map for the current mode.');
    buffer.writeln('  double? size(String groupPath, String token) {');
    buffer.writeln('    final path = "\$_mode.sizes.\$groupPath.\$token";');
    buffer.writeln('    final override = _overrides[path];');
    buffer.writeln('    if (override is double) return override;');
    buffer.writeln();
    buffer.writeln(
      r"    final pascalPath = groupPath.split('.').map((s) => _pascalCase(s)).join();",
    );
    buffer.writeln("    if (_mode == 'dark') {");
    buffer.writeln('      switch (pascalPath) {');
    _generateSizeCaseStatements(buffer, sizeTree, 'dark');
    buffer.writeln('      }');
    buffer.writeln('    } else {');
    buffer.writeln('      switch (pascalPath) {');
    _generateSizeCaseStatements(buffer, sizeTree, 'light');
    buffer.writeln('      }');
    buffer.writeln('    }');
    buffer.writeln('    return null;');
    buffer.writeln('  }');
    buffer.writeln();

    // Generate typography lookup method.
    buffer.writeln(
      '  /// Looks up a text style by full group path and token name.',
    );
    buffer.writeln('  ///');
    buffer.writeln(
      '  /// Returns the override if one exists, otherwise returns the style',
    );
    buffer.writeln('  /// from the const map for the current mode.');
    buffer.writeln('  TextStyle? textStyle(String groupPath, String token) {');
    buffer.writeln(
      '    final path = "\$_mode.typography.\$groupPath.\$token";',
    );
    buffer.writeln('    final override = _overrides[path];');
    buffer.writeln('    if (override is TextStyle) return override;');
    buffer.writeln();
    buffer.writeln(
      r"    final pascalPath = groupPath.split('.').map((s) => _pascalCase(s)).join();",
    );
    buffer.writeln("    if (_mode == 'dark') {");
    buffer.writeln('      switch (pascalPath) {');
    _generateTypographyCaseStatements(buffer, typographyTree, 'dark');
    buffer.writeln('      }');
    buffer.writeln('    } else {');
    buffer.writeln('      switch (pascalPath) {');
    _generateTypographyCaseStatements(buffer, typographyTree, 'light');
    buffer.writeln('      }');
    buffer.writeln('    }');
    buffer.writeln('    return null;');
    buffer.writeln('  }');

    // Add helper method for pascal case conversion
    buffer.writeln();
    buffer.writeln('  /// Converts a string to PascalCase.');
    buffer.writeln('  String _pascalCase(String input) {');
    buffer.writeln('    if (input.isEmpty) return input;');
    buffer.writeln('    return input[0].toUpperCase() + input.substring(1);');
    buffer.writeln('  }');
    buffer.writeln('}');

    return buffer.toString();
  }

  void _generateColorCaseStatements(
    StringBuffer buffer,
    List<TokenGroupNode> tree,
    String mode, {
    String prefix = '',
  }) {
    for (final node in tree) {
      final pascalName = _pascalCasePath(node.fullPath);
      if (node.children.isEmpty) {
        // Leaf node
        buffer.writeln(
          '        case "$pascalName": return _${mode}Color$pascalName[token];',
        );
      }
      // Recurse into children
      _generateColorCaseStatements(buffer, node.children, mode, prefix: prefix);
    }
  }

  void _generateSizeCaseStatements(
    StringBuffer buffer,
    List<TokenGroupNode> tree,
    String mode, {
    String prefix = '',
  }) {
    for (final node in tree) {
      final pascalName = _pascalCasePath(node.fullPath);
      if (node.children.isEmpty) {
        buffer.writeln(
          '        case "$pascalName": return _${mode}Size$pascalName[token];',
        );
      }
      _generateSizeCaseStatements(buffer, node.children, mode, prefix: prefix);
    }
  }

  void _generateTypographyCaseStatements(
    StringBuffer buffer,
    List<TokenGroupNode> tree,
    String mode, {
    String prefix = '',
  }) {
    for (final node in tree) {
      final pascalName = _pascalCasePath(node.fullPath);
      // Typography generates maps for leaf nodes with tokens
      if (node.group.tokenPaths.isNotEmpty) {
        buffer.writeln(
          '        case "$pascalName": return _${mode}Typography$pascalName[token];',
        );
      }
      _generateTypographyCaseStatements(
        buffer,
        node.children,
        mode,
        prefix: prefix,
      );
    }
  }

  /// Generates color resolver classes recursively for the tree structure.
  String _generateColorResolvers(
    TokenGroupNode node,
    List<String> modes,
    Map<String, List<DesignToken>> modeTokens,
  ) {
    final buffer = StringBuffer();

    // Generate the resolver class for this node
    final className = '_${_pascalCasePath(node.fullPath)}Colors';
    final fields =
        node.group.tokenPaths.map((p) => _fieldNameFromPath(p)).toSet().toList()
          ..sort();

    // Only generate class if it has fields or children
    if (fields.isNotEmpty || node.children.isNotEmpty) {
      // Use group description if available, otherwise use default
      final groupDesc = _groupDescriptions['$_primaryMode.color.${node.fullPath}'];
      if (groupDesc != null && groupDesc.isNotEmpty) {
        final wrappedLines = _wrapText(groupDesc, maxWidth: 78, prefix: '/// ');
        for (final line in wrappedLines) {
          buffer.writeln(line);
        }
      } else {
        buffer.writeln(
          '/// Provides typed access to the "${node.fullPath}" color tokens.',
        );
      }
      buffer.writeln('class $className {');
      buffer.writeln('  final _TokenStore _store;');
      buffer.writeln();
      buffer.writeln('  const $className(this._store);');
      buffer.writeln();

      // Generate getters for direct tokens
      final primaryMode = modes.first;
      final primaryTokens = modeTokens[primaryMode] ?? [];
      for (final field in fields) {
        // Find the token for this field to get the description
        final token = primaryTokens.firstWhere(
          (t) => t.path.endsWith('.${node.fullPath}.$field'),
          orElse: () => DesignToken(
            path: '${node.fullPath}.$field',
            type: 'color',
            value: '',
            raw: {},
          ),
        );
        // Add description comment if available
        if (token.description != null && token.description!.isNotEmpty) {
          buffer.writeln('  /// ${token.description}');
        }
        buffer.writeln(
          "  Color get $field => _store.color('${node.fullPath}', '$field')!;",
        );
      }

      // Generate sub-accessors for children
      for (final child in node.children) {
        final childClass = '_${_pascalCasePath(child.fullPath)}Colors';
        final childField = _camelCase(child.name);
        buffer.writeln('  $childClass get $childField => $childClass(_store);');
      }

      buffer.writeln('}');
    }

    // Recursively generate classes for children
    for (final child in node.children) {
      buffer.writeln();
      buffer.writeln(_generateColorResolvers(child, modes, modeTokens));
    }

    return buffer.toString();
  }

  /// Generates size resolver classes recursively for the tree structure.
  String _generateSizeResolvers(
    TokenGroupNode node,
    List<String> modes,
    Map<String, List<DesignToken>> modeTokens,
  ) {
    final buffer = StringBuffer();

    final className = '_${_pascalCasePath(node.fullPath)}Sizes';
    final fields =
        node.group.tokenPaths.map((p) => _fieldNameFromPath(p)).toSet().toList()
          ..sort();

    final primaryMode = modes.first;
    final primaryTokens = modeTokens[primaryMode] ?? [];

    if (fields.isNotEmpty || node.children.isNotEmpty) {
      // Use group description if available, otherwise use default
      final groupDesc = _groupDescriptions['$_primaryMode.sizes.${node.fullPath}'];
      if (groupDesc != null && groupDesc.isNotEmpty) {
        final wrappedLines = _wrapText(groupDesc, maxWidth: 78, prefix: '/// ');
        for (final line in wrappedLines) {
          buffer.writeln(line);
        }
      } else {
        buffer.writeln(
          '/// Provides typed access to the "${node.fullPath}" size tokens.',
        );
      }
      buffer.writeln('class $className {');
      buffer.writeln('  final _TokenStore _store;');
      buffer.writeln();
      buffer.writeln('  const $className(this._store);');
      buffer.writeln();

      // Generate getters for direct tokens with fallback values
      for (final field in fields) {
        // Find the token for this field to get the fallback value
        final token = primaryTokens.firstWhere(
          (t) => t.path.endsWith('.${node.fullPath}.$field'),
          orElse: () => DesignToken(
            path: '${node.fullPath}.$field',
            type: 'dimension',
            value: 0.0,
            raw: {},
          ),
        );

        double fallbackValue;
        if (token.value is num) {
          fallbackValue = (token.value as num).toDouble();
        } else if (token.value is String) {
          final parsed = double.tryParse(
            (token.value as String).replaceAll(RegExp(r'(px|rem|em)$'), ''),
          );
          fallbackValue = parsed ?? 0.0;
        } else {
          fallbackValue = 0.0;
        }

        // Add description comment if available
        if (token.description != null && token.description!.isNotEmpty) {
          buffer.writeln('  /// ${token.description}');
        }
        buffer.writeln(
          "  double get $field => _store.size('${node.fullPath}', '$field') ?? $fallbackValue;",
        );
      }

      // Generate sub-accessors for children
      for (final child in node.children) {
        final childClass = '_${_pascalCasePath(child.fullPath)}Sizes';
        final childField = _camelCase(child.name);
        buffer.writeln('  $childClass get $childField => $childClass(_store);');
      }

      buffer.writeln('}');
    }

    // Recursively generate classes for children
    for (final child in node.children) {
      buffer.writeln();
      buffer.writeln(_generateSizeResolvers(child, modes, modeTokens));
    }

    return buffer.toString();
  }

  /// Generates typography resolver classes recursively for the tree structure.
  String _generateTypographyResolvers(
    TokenGroupNode node,
    List<String> modes,
    Map<String, List<DesignToken>> modeTokens,
  ) {
    final buffer = StringBuffer();

    final className = '_${_pascalCasePath(node.fullPath)}Typography';
    final fields =
        node.group.tokenPaths.map((p) => _fieldNameFromPath(p)).toSet().toList()
          ..sort();

    final primaryMode = modes.first;
    final primaryTokens = modeTokens[primaryMode] ?? [];

    if (fields.isNotEmpty || node.children.isNotEmpty) {
      // Use group description if available, otherwise use default
      final groupDesc = _groupDescriptions['$_primaryMode.typography.${node.fullPath}'];
      if (groupDesc != null && groupDesc.isNotEmpty) {
        final wrappedLines = _wrapText(groupDesc, maxWidth: 78, prefix: '/// ');
        for (final line in wrappedLines) {
          buffer.writeln(line);
        }
      } else {
        buffer.writeln(
          '/// Provides typed access to the "${node.fullPath}" typography tokens.',
        );
      }
      buffer.writeln('class $className {');
      buffer.writeln('  final _TokenStore _store;');
      buffer.writeln();
      buffer.writeln('  const $className(this._store);');
      buffer.writeln();

      // Generate getters for direct tokens with fallback TextStyle values
      for (final field in fields) {
        final token = primaryTokens.firstWhere(
          (t) => t.path.endsWith('.${node.fullPath}.$field'),
          orElse: () => DesignToken(
            path: '${node.fullPath}.$field',
            type: 'typography',
            value: {'fontSize': 14.0, 'fontWeight': 400},
            raw: {},
          ),
        );

        String fallbackValue;
        final textStyle = _generateTextStyle(token.value);
        if (textStyle != null) {
          fallbackValue = textStyle;
        } else {
          fallbackValue = 'const TextStyle(fontSize: 14)';
        }

        // Add description comment if available
        if (token.description != null && token.description!.isNotEmpty) {
          buffer.writeln('  /// ${token.description}');
        }
        buffer.writeln(
          "  TextStyle get $field => _store.textStyle('${node.fullPath}', '$field') ?? $fallbackValue;",
        );
      }

      // Generate sub-accessors for children
      for (final child in node.children) {
        final childClass = '_${_pascalCasePath(child.fullPath)}Typography';
        final childField = _camelCase(child.name);
        buffer.writeln('  $childClass get $childField => $childClass(_store);');
      }

      buffer.writeln('}');
    }

    // Recursively generate classes for children
    for (final child in node.children) {
      buffer.writeln();
      buffer.writeln(_generateTypographyResolvers(child, modes, modeTokens));
    }

    return buffer.toString();
  }

  /// Generates the main ${config.className} class.
  ///
  /// This is the primary theme extension that applications interact with.
  /// It provides factory constructors for light/dark modes and category
  /// accessors for colors, sizes, and typography.
  String _generateAppTheme(
    List<TokenGroupNode> colorTree,
    List<TokenGroupNode> sizeTree,
    List<TokenGroupNode> typographyTree,
  ) {
    final buffer = StringBuffer();
    final className = config.className;

    buffer.writeln('/// The main theme extension for the application.');
    buffer.writeln('///');
    buffer.writeln(
      '/// Use [$className.dark()] or [$className.light()] to create theme instances.',
    );
    buffer.writeln(
      '/// Access token values via the [colors], [sizes], and [typography] getters.',
    );
    buffer.writeln('class $className extends ThemeExtension<$className> {');
    buffer.writeln('  final _TokenStore _store;');
    buffer.writeln();
    buffer.writeln('  $className(this._store);');
    buffer.writeln();

    // Category accessors.
    buffer.writeln('  // Category accessors - entry points for token values.');
    buffer.writeln('  // --------------------------------------------------');
    buffer.writeln('  /// Access all color tokens including brand, foreground, action, canvas, etc.');
    buffer.writeln('  _ThemeColors get colors => _ThemeColors(_store);');
    buffer.writeln('  /// Access all size tokens including padding, spacing, radius, typography, etc.');
    buffer.writeln('  _ThemeSizes get sizes => _ThemeSizes(_store);');
    buffer.writeln('  /// Access all typography tokens including display, headline, title, body, etc.');
    buffer.writeln(
      '  _ThemeTypography get typography => _ThemeTypography(_store);',
    );
    buffer.writeln();

    // Factory constructors.
    buffer.writeln('  /// Creates a theme instance for dark mode.');
    buffer.writeln(
      "  factory $className.dark() => $className(_TokenStore(mode: 'dark'));",
    );
    buffer.writeln();
    buffer.writeln('  /// Creates a theme instance for light mode.');
    buffer.writeln(
      "  factory $className.light() => $className(_TokenStore(mode: 'light'));",
    );
    buffer.writeln();

    // Static of() method for convenient context access.
    buffer.writeln(
      '  /// Retrieves the [$className] from the given [context].',
    );
    buffer.writeln('  ///');
    buffer.writeln('  /// This is a convenience method equivalent to:');
    buffer.writeln('  /// `Theme.of(context).extension<$className>()!`');
    buffer.writeln('  ///');
    buffer.writeln(
      '  /// Throws an error if no [$className] is found in the theme.',
    );
    buffer.writeln('  static $className of(BuildContext context) {');
    buffer.writeln(
      '    final theme = Theme.of(context).extension<$className>();',
    );
    buffer.writeln(
      "    assert(theme != null, 'No $className found in context');",
    );
    buffer.writeln('    return theme!;');
    buffer.writeln('  }');
    buffer.writeln();

    // copyWith - required by ThemeExtension but not used for overrides.
    buffer.writeln('  @override');
    buffer.writeln('$className copyWith() => $className(_store);');
    buffer.writeln();

    // lerp - required by ThemeExtension, returns this (no animation).
    buffer.writeln('  @override');
    buffer.writeln(
      '$className lerp(ThemeExtension<dynamic>? other, double t) => this;',
    );
    buffer.writeln();

    // Equality operators.
    buffer.writeln('  @override');
    buffer.writeln(
      '  bool operator ==(Object other) => other is $className && other._store == _store;',
    );
    buffer.writeln();
    buffer.writeln('  @override');
    buffer.writeln('  int get hashCode => _store.hashCode;');
    buffer.writeln('}');

    return buffer.toString();
  }

  /// Generates the theme helper classes that bridge AppTheme to resolvers.
  ///
  /// Creates _ThemeColors, _ThemeSizes, and _ThemeTypography classes.
  /// Each provides sub-group accessors recursively.
  String _generateThemeHelperClasses(
    List<TokenGroupNode> colorTree,
    List<TokenGroupNode> sizeTree,
    List<TokenGroupNode> typographyTree,
  ) {
    final buffer = StringBuffer();

    // Generate _ThemeColors - provides access to color groups.
    buffer.writeln();
    buffer.writeln('/// Provides access to all color category groups.');
    buffer.writeln('class _ThemeColors {');
    buffer.writeln('  final _TokenStore _store;');
    buffer.writeln('  const _ThemeColors(this._store);');
    for (final node in colorTree) {
      final field = _camelCase(node.name);
      final className = '_${_pascalCasePath(node.fullPath)}Colors';
      // Look up group description for this color category
      final groupPath = '$_primaryMode.color.${node.fullPath}';
      final groupDesc = _groupDescriptions[groupPath];
      if (groupDesc != null && groupDesc.isNotEmpty) {
        final wrappedLines = _wrapText(groupDesc, maxWidth: 78, prefix: '  /// ');
        for (final line in wrappedLines) {
          buffer.writeln(line);
        }
      }
      buffer.writeln('  $className get $field => $className(_store);');
    }
    buffer.writeln('}');

    // Generate _ThemeSizes - provides access to size groups.
    buffer.writeln();
    buffer.writeln('/// Provides access to all size category groups.');
    buffer.writeln('class _ThemeSizes {');
    buffer.writeln('  final _TokenStore _store;');
    buffer.writeln('  const _ThemeSizes(this._store);');
    for (final node in sizeTree) {
      final field = _camelCase(node.name);
      final className = '_${_pascalCasePath(node.fullPath)}Sizes';
      // Look up group description for this size category
      final groupPath = '$_primaryMode.sizes.${node.fullPath}';
      final groupDesc = _groupDescriptions[groupPath];
      if (groupDesc != null && groupDesc.isNotEmpty) {
        final wrappedLines = _wrapText(groupDesc, maxWidth: 78, prefix: '  /// ');
        for (final line in wrappedLines) {
          buffer.writeln(line);
        }
      }
      buffer.writeln('  $className get $field => $className(_store);');
    }
    buffer.writeln('}');

    // Generate _ThemeTypography - provides access to typography groups.
    buffer.writeln();
    buffer.writeln('/// Provides access to all typography category groups.');
    buffer.writeln('class _ThemeTypography {');
    buffer.writeln('  final _TokenStore _store;');
    buffer.writeln('  const _ThemeTypography(this._store);');
    for (final node in typographyTree) {
      final field = _camelCase(node.name);
      final className = '_${_pascalCasePath(node.fullPath)}Typography';
      // Look up group description for this typography category
      final groupPath = '$_primaryMode.typography.${node.fullPath}';
      final groupDesc = _groupDescriptions[groupPath];
      if (groupDesc != null && groupDesc.isNotEmpty) {
        final wrappedLines = _wrapText(groupDesc, maxWidth: 78, prefix: '  /// ');
        for (final line in wrappedLines) {
          buffer.writeln(line);
        }
      }
      buffer.writeln('  $className get $field => $className(_store);');
    }
    buffer.writeln('}');

    return buffer.toString();
  }

  /// Generates the ${config.className}Notifier and ${config.className}Provider for state management.
  ///
  /// Creates:
  /// - [${config.className}Notifier]: A ChangeNotifier that manages the current theme mode
  ///   and applies server-side overrides. It provides themeData for MaterialApp
  ///   and methods to toggle modes and manage overrides.
  /// - [${config.className}Provider]: An InheritedNotifier widget that provides
  ///   [${config.className}Notifier] to the widget tree via `of(context)`.
  String _generateThemeProvider(List<String> modes) {
    final buffer = StringBuffer();
    final modeEnum = modes.map((m) => m.toLowerCase()).join(', ');
    final className = config.className;
    final notifierClassName = '${className}Notifier';
    final providerClassName = '${className}Provider';
    final modeClassName = '${className}Mode';

    buffer.writeln('/// Available theme modes.');
    buffer.writeln('enum $modeClassName { $modeEnum }');
    buffer.writeln();

    buffer.writeln('/// Manages theme state and server-side overrides.');
    buffer.writeln('///');
    buffer.writeln(
      '/// Use this as a ChangeNotifier in your widget tree. It provides',
    );
    buffer.writeln(
      '/// [themeData] for MaterialApp and handles mode switching and',
    );
    buffer.writeln('/// applying server overrides dynamically.');
    buffer.writeln('class $notifierClassName extends ChangeNotifier {');
    buffer.writeln(
      '  $notifierClassName({$modeClassName initialMode = $modeClassName.dark})',
    );
    buffer.writeln('      : _mode = initialMode,');
    buffer.writeln('        _store = _TokenStore(mode: initialMode.name),');
    buffer.writeln(
      '        _theme = $className(_TokenStore(mode: initialMode.name));',
    );
    buffer.writeln();
    buffer.writeln('  $modeClassName _mode;');
    buffer.writeln('  final _TokenStore _store;');
    buffer.writeln('$className _theme;');
    buffer.writeln();
    buffer.writeln('  /// The current theme mode (dark or light).');
    buffer.writeln('  $modeClassName get mode => _mode;');
    buffer.writeln('  /// The current $className instance.');
    buffer.writeln('  $className get theme => _theme;');
    buffer.writeln();

    // Generate themeData getter.
    buffer.writeln(
      '  /// Material ThemeData derived from the current $className.',
    );
    buffer.writeln('  ThemeData get themeData {');
    buffer.writeln('    final isDark = _mode == $modeClassName.dark;');
    buffer.writeln('    return ThemeData(');
    buffer.writeln(
      '      brightness: isDark ? Brightness.dark : Brightness.light,',
    );
    buffer.writeln('      extensions: [_theme],');
    buffer.writeln('    );');
    buffer.writeln('  }');
    buffer.writeln();

    // Mode setter.
    buffer.writeln('  set mode($modeClassName mode) {');
    buffer.writeln('    if (_mode != mode) {');
    buffer.writeln('      _mode = mode;');
    buffer.writeln('      _store.mode = mode.name;');
    buffer.writeln('      _theme = $className(_store);');
    buffer.writeln('      notifyListeners();');
    buffer.writeln('    }');
    buffer.writeln('  }');
    buffer.writeln();

    // Toggle method.
    buffer.writeln('  /// Toggles between light and dark modes.');
    buffer.writeln('  void toggleMode() {');
    buffer.writeln(
      '    mode = _mode == $modeClassName.light ? $modeClassName.dark : $modeClassName.light;',
    );
    buffer.writeln('  }');
    buffer.writeln();

    // Apply overrides.
    buffer.writeln('  /// Applies server-side theme overrides.');
    buffer.writeln('  ///');
    buffer.writeln(
      '  /// [overrides] is a map of token paths to values, e.g.,',
    );
    buffer.writeln(
      '  /// `{ "dark.color.brand.primary": Color(0xFFFF0000) }`.',
    );
    buffer.writeln('  void applyOverrides(Map<String, dynamic> overrides) {');
    buffer.writeln(
      '    final merged = Map<String, dynamic>.from(_store.overrides);',
    );
    buffer.writeln('    merged.addAll(overrides);');
    buffer.writeln('    _store.setOverrides(merged);');
    buffer.writeln('    _theme = $className(_store);');
    buffer.writeln('    notifyListeners();');
    buffer.writeln('  }');
    buffer.writeln();

    // Clear overrides.
    buffer.writeln('  /// Clears all server-side overrides.');
    buffer.writeln('  void clearOverrides() {');
    buffer.writeln('    _store.clearOverrides();');
    buffer.writeln('    _theme = $className(_store);');
    buffer.writeln('    notifyListeners();');
    buffer.writeln('  }');
    buffer.writeln('}');
    buffer.writeln();

    // ${className}Provider (InheritedNotifier)
    buffer.writeln(
      '/// Provides [$notifierClassName] to the widget tree via [InheritedNotifier].',
    );
    buffer.writeln('///');
    buffer.writeln(
      '/// Use this widget to inject theme state into your app. Access the notifier',
    );
    buffer.writeln(
      '/// via `$providerClassName.of(context)` or use the extension methods on [BuildContext].',
    );
    buffer.writeln('///');
    buffer.writeln(
      '/// When using the [builder] constructor, widgets rebuild automatically when theme changes.',
    );
    buffer.writeln(
      'class $providerClassName extends InheritedNotifier<$notifierClassName> {',
    );
    buffer.writeln('  const $providerClassName({');
    buffer.writeln('    super.key,');
    buffer.writeln('    required super.notifier,');
    buffer.writeln('    required super.child,');
    buffer.writeln('  });');
    buffer.writeln();

    buffer.writeln(
      '  /// Creates a [$providerClassName] with a builder that rebuilds when theme changes.',
    );
    buffer.writeln('  ///');
    buffer.writeln(
      '  /// The [builder] callback is called whenever the theme notifier notifies listeners.',
    );
    buffer.writeln(
      '  /// This eliminates the need for [AnimatedBuilder] or similar widgets.',
    );
    buffer.writeln('  static Widget builder({');
    buffer.writeln('    Key? key,');
    buffer.writeln('    required $notifierClassName notifier,');
    buffer.writeln(
      '    required Widget Function(BuildContext context, $notifierClassName notifier) builder,',
    );
    buffer.writeln('  }) {');
    buffer.writeln('    return $providerClassName(');
    buffer.writeln('      key: key,');
    buffer.writeln('      notifier: notifier,');
    buffer.writeln('      child: _${className}Builder(');
    buffer.writeln('        notifier: notifier,');
    buffer.writeln('        builder: builder,');
    buffer.writeln('      ),');
    buffer.writeln('    );');
    buffer.writeln('  }');
    buffer.writeln();

    buffer.writeln(
      '  /// Retrieves the [$notifierClassName] from the widget tree.',
    );
    buffer.writeln('  ///');
    buffer.writeln(
      '  /// Returns null if no [$providerClassName] is found in the ancestry.',
    );
    buffer.writeln(
      '  static $notifierClassName? maybeOf(BuildContext context) {',
    );
    buffer.writeln(
      '    return context.dependOnInheritedWidgetOfExactType<$providerClassName>()?.notifier;',
    );
    buffer.writeln('  }');
    buffer.writeln();

    buffer.writeln(
      '  /// Retrieves the [$notifierClassName] from the widget tree.',
    );
    buffer.writeln('  ///');
    buffer.writeln(
      '  /// Throws an error if no [$providerClassName] is found in the ancestry.',
    );
    buffer.writeln('  static $notifierClassName of(BuildContext context) {');
    buffer.writeln('    final notifier = maybeOf(context);');
    buffer.writeln(
      "    assert(notifier != null, 'No $providerClassName found in context');",
    );
    buffer.writeln('    return notifier!;');
    buffer.writeln('  }');
    buffer.writeln('}');
    buffer.writeln();

    // _${className}Builder helper widget
    buffer.writeln(
      '/// Internal widget that rebuilds when [$notifierClassName] changes.',
    );
    buffer.writeln('class _${className}Builder extends StatefulWidget {');
    buffer.writeln('  final $notifierClassName notifier;');
    buffer.writeln(
      '  final Widget Function(BuildContext context, $notifierClassName notifier) builder;',
    );
    buffer.writeln();
    buffer.writeln('  const _${className}Builder({');
    buffer.writeln('    required this.notifier,');
    buffer.writeln('    required this.builder,');
    buffer.writeln('  });');
    buffer.writeln();
    buffer.writeln('  @override');
    buffer.writeln(
      '  State<_${className}Builder> createState() => _${className}BuilderState();',
    );
    buffer.writeln('}');
    buffer.writeln();

    buffer.writeln(
      'class _${className}BuilderState extends State<_${className}Builder> {',
    );
    buffer.writeln('  @override');
    buffer.writeln('  void initState() {');
    buffer.writeln('    super.initState();');
    buffer.writeln('    widget.notifier.addListener(_onThemeChanged);');
    buffer.writeln('  }');
    buffer.writeln();
    buffer.writeln('  @override');
    buffer.writeln('  void didUpdateWidget(_${className}Builder oldWidget) {');
    buffer.writeln('    super.didUpdateWidget(oldWidget);');
    buffer.writeln('    if (widget.notifier != oldWidget.notifier) {');
    buffer.writeln('      oldWidget.notifier.removeListener(_onThemeChanged);');
    buffer.writeln('      widget.notifier.addListener(_onThemeChanged);');
    buffer.writeln('    }');
    buffer.writeln('  }');
    buffer.writeln();
    buffer.writeln('  @override');
    buffer.writeln('  void dispose() {');
    buffer.writeln('    widget.notifier.removeListener(_onThemeChanged);');
    buffer.writeln('    super.dispose();');
    buffer.writeln('  }');
    buffer.writeln();
    buffer.writeln('  void _onThemeChanged() {');
    buffer.writeln('    setState(() {});');
    buffer.writeln('  }');
    buffer.writeln();
    buffer.writeln('  @override');
    buffer.writeln('  Widget build(BuildContext context) {');
    buffer.writeln('    return widget.builder(context, widget.notifier);');
    buffer.writeln('  }');
    buffer.writeln('}');

    return buffer.toString();
  }

  /// Generates the BuildContext extension for easy theme access.
  ///
  /// Adds:
  /// - `context.theme` getter that retrieves the ${config.className} from
  ///   the current build context's ThemeData extensions.
  /// - `context.themeNotifier` getter that retrieves the ${config.className}Notifier
  ///   from the ${config.className}Provider in the widget tree.
  String _generateContextExtensions() {
    final className = config.className;
    final notifierClassName = '${className}Notifier';
    final providerClassName = '${className}Provider';

    return '''
/// Extension methods on [BuildContext] for convenient theme access.
extension ${className}ContextExtensions on BuildContext {
  /// Retrieves the [$className] from the current context.
  ///
  /// This is equivalent to `Theme.of(context).extension<$className>()!` but
  /// provides a more concise syntax: `context.theme`.
  $className get theme {
    return Theme.of(this).extension<$className>()!;
  }

  /// Retrieves the [$notifierClassName] from the current context.
  ///
  /// This is equivalent to `$providerClassName.of(context)` but
  /// provides a more concise syntax: `context.themeNotifier`.
  $notifierClassName get themeNotifier {
    return $providerClassName.of(this);
  }

  /// Retrieves the [$notifierClassName] from the current context (nullable).
  ///
  /// Returns null if no [$providerClassName] is found in the ancestry.
  $notifierClassName? get themeNotifierMaybe {
    return $providerClassName.maybeOf(this);
  }
}''';
  }

  // --- Token Value Helpers ---

  /// Generates a TextStyle constructor call from a token's value map.
  ///
  /// Parses fontSize, fontWeight, height, letterSpacing, fontFamily,
  /// and color properties from the token value.
  String? _generateTextStyle(dynamic value) {
    if (value is! Map<String, dynamic>) return null;

    final props = <String>[];

    if (value['fontSize'] is num) {
      props.add('fontSize: ${value['fontSize']}');
    }
    if (value['fontWeight'] is int) {
      props.add('fontWeight: FontWeight.w${value['fontWeight']}');
    }
    if (value['height'] is num) {
      props.add('height: ${value['height']}');
    }
    if (value['letterSpacing'] is num) {
      props.add('letterSpacing: ${value['letterSpacing']}');
    }
    if (value['fontFamily'] is String) {
      props.add("fontFamily: '${value['fontFamily']}'");
    }
    if (value['color'] is String) {
      final colorVal = TokenParser.parseColor(value['color']);
      if (colorVal != null) {
        props.add(
          'color: Color(0x${colorVal.toRadixString(16).padLeft(8, '0').toUpperCase()})',
        );
      }
    }

    if (props.isEmpty) return null;
    return 'TextStyle(${props.join(', ')})';
  }

  /// Extracts the field name from a token path (the last segment).
  String _fieldNameFromPath(String path) {
    return path.split('.').last;
  }

  // --- String Case Converters ---

  /// Converts a string to camelCase (e.g., "font-size" -> "fontSize").
  String _camelCase(String input) {
    if (input.isEmpty) return input;
    final parts = input.split(RegExp(r'[-_.]'));
    if (parts.isEmpty) return input;
    return parts.first.toLowerCase() +
        parts
            .skip(1)
            .map(
              (p) => p.isEmpty ? '' : '${p[0].toUpperCase()}${p.substring(1)}',
            )
            .join();
  }

  /// Converts a string to PascalCase (e.g., "font-size" -> "FontSize").
  String _pascalCase(String input) {
    if (input.isEmpty) return input;
    final parts = input.split(RegExp(r'[-_.]'));
    return parts
        .map((p) => p.isEmpty ? '' : '${p[0].toUpperCase()}${p.substring(1)}')
        .join();
  }

  /// Converts a dot-separated path to PascalCase.
  /// e.g., "display.h1" -> "DisplayH1"
  String _pascalCasePath(String path) {
    if (path.isEmpty) return path;
    return path.split('.').map((p) => _pascalCase(p)).join();
  }

  /// Strips the mode prefix from a token path.
  /// e.g., "light.color.brand.primary" -> "color.brand.primary"
  String _stripModePrefix(String path) {
    final parts = path.split('.');
    if (parts.isEmpty) return path;
    // Remove first part if it's a known mode
    if (parts[0] == 'light' || parts[0] == 'dark') {
      return parts.sublist(1).join('.');
    }
    return path;
  }

  /// Wraps text at a maximum width, returning lines with the given prefix.
  /// Used for formatting long descriptions in generated comments.
  List<String> _wrapText(String text, {int maxWidth = 80, String prefix = '// '}) {
    final words = text.split(' ');
    final lines = <String>[];
    var currentLine = prefix;

    for (final word in words) {
      // Check if adding this word would exceed max width
      if (currentLine.length + word.length + 1 > maxWidth) {
        lines.add(currentLine.trimRight());
        currentLine = '$prefix$word ';
      } else {
        currentLine += '$word ';
      }
    }

    // Add the last line if not empty
    if (currentLine.trimRight() != prefix.trimRight()) {
      lines.add(currentLine.trimRight());
    }

    return lines;
  }
}
