// GENERATED CODE - DO NOT MODIFY MANUALLY
// Generated by design_builder
//
// Modern E-Commerce Theme - A comprehensive design system with semantic
// tokens for colors, sizes, and typography supporting both light and dark
// modes.
//
// This file contains theme configuration generated from design tokens.
// To update, modify the source token files and rebuild.
//
// ignore_for_file: library_private_types_in_public_api, unnecessary_getters_setters

import 'package:flutter/material.dart';

/// The main theme extension for the application.
///
/// Use [AppTheme.dark()] or [AppTheme.light()] to create theme instances.
/// Access token values via the [colors], [sizes], and [typography] getters.
class AppTheme extends ThemeExtension<AppTheme> {
  final _TokenStore _store;

  AppTheme(this._store);

  // Category accessors - entry points for token values.
  // --------------------------------------------------
  /// Access all color tokens including brand, foreground, action, canvas, etc.
  _ThemeColors get colors => _ThemeColors(_store);

  /// Access all size tokens including padding, spacing, radius, typography, etc.
  _ThemeSizes get sizes => _ThemeSizes(_store);

  /// Access all typography tokens including display, headline, title, body, etc.
  _ThemeTypography get typography => _ThemeTypography(_store);

  /// Creates a theme instance for dark mode.
  factory AppTheme.dark() => AppTheme(_TokenStore(mode: 'dark'));

  /// Creates a theme instance for light mode.
  factory AppTheme.light() => AppTheme(_TokenStore(mode: 'light'));

  /// Retrieves the [AppTheme] from the given [context].
  ///
  /// This is a convenience method equivalent to:
  /// `Theme.of(context).extension<AppTheme>()!`
  ///
  /// Throws an error if no [AppTheme] is found in the theme.
  static AppTheme of(BuildContext context) {
    final theme = Theme.of(context).extension<AppTheme>();
    assert(theme != null, 'No AppTheme found in context');
    return theme!;
  }

  @override
  AppTheme copyWith() => AppTheme(_store);

  @override
  AppTheme lerp(ThemeExtension<dynamic>? other, double t) => this;

  @override
  bool operator ==(Object other) => other is AppTheme && other._store == _store;

  @override
  int get hashCode => _store.hashCode;
}

/// Available theme modes.
enum AppThemeMode { dark, light }

/// Manages theme state and server-side overrides.
///
/// Use this as a ChangeNotifier in your widget tree. It provides
/// [themeData] for MaterialApp and handles mode switching and
/// applying server overrides dynamically.
class AppThemeNotifier extends ChangeNotifier {
  AppThemeNotifier({AppThemeMode initialMode = AppThemeMode.dark})
    : _mode = initialMode,
      _store = _TokenStore(mode: initialMode.name),
      _theme = AppTheme(_TokenStore(mode: initialMode.name));

  AppThemeMode _mode;
  final _TokenStore _store;
  AppTheme _theme;

  /// The current theme mode (dark or light).
  AppThemeMode get mode => _mode;

  /// The current AppTheme instance.
  AppTheme get theme => _theme;

  /// Material ThemeData derived from the current AppTheme.
  ThemeData get themeData {
    final isDark = _mode == AppThemeMode.dark;
    return ThemeData(
      brightness: isDark ? Brightness.dark : Brightness.light,
      extensions: [_theme],
    );
  }

  set mode(AppThemeMode mode) {
    if (_mode != mode) {
      _mode = mode;
      _store.mode = mode.name;
      _theme = AppTheme(_store);
      notifyListeners();
    }
  }

  /// Toggles between light and dark modes.
  void toggleMode() {
    mode = _mode == AppThemeMode.light ? AppThemeMode.dark : AppThemeMode.light;
  }

  /// Applies server-side theme overrides.
  ///
  /// [overrides] is a map of token paths to values, e.g.,
  /// `{ "dark.color.brand.primary": Color(0xFFFF0000) }`.
  void applyOverrides(Map<String, dynamic> overrides) {
    final merged = Map<String, dynamic>.from(_store.overrides);
    merged.addAll(overrides);
    _store.setOverrides(merged);
    _theme = AppTheme(_store);
    notifyListeners();
  }

  /// Clears all server-side overrides.
  void clearOverrides() {
    _store.clearOverrides();
    _theme = AppTheme(_store);
    notifyListeners();
  }
}

/// Provides [AppThemeNotifier] to the widget tree via [InheritedNotifier].
///
/// Use this widget to inject theme state into your app. Access the notifier
/// via `AppThemeProvider.of(context)` or use the extension methods on [BuildContext].
///
/// When using the [builder] constructor, widgets rebuild automatically when theme changes.
class AppThemeProvider extends InheritedNotifier<AppThemeNotifier> {
  const AppThemeProvider({
    super.key,
    required super.notifier,
    required super.child,
  });

  /// Creates a [AppThemeProvider] with a builder that rebuilds when theme changes.
  ///
  /// The [builder] callback is called whenever the theme notifier notifies listeners.
  /// This eliminates the need for [AnimatedBuilder] or similar widgets.
  static Widget builder({
    Key? key,
    required AppThemeNotifier notifier,
    required Widget Function(BuildContext context, AppThemeNotifier notifier)
    builder,
  }) {
    return AppThemeProvider(
      key: key,
      notifier: notifier,
      child: _AppThemeBuilder(notifier: notifier, builder: builder),
    );
  }

  /// Retrieves the [AppThemeNotifier] from the widget tree.
  ///
  /// Returns null if no [AppThemeProvider] is found in the ancestry.
  static AppThemeNotifier? maybeOf(BuildContext context) {
    return context
        .dependOnInheritedWidgetOfExactType<AppThemeProvider>()
        ?.notifier;
  }

  /// Retrieves the [AppThemeNotifier] from the widget tree.
  ///
  /// Throws an error if no [AppThemeProvider] is found in the ancestry.
  static AppThemeNotifier of(BuildContext context) {
    final notifier = maybeOf(context);
    assert(notifier != null, 'No AppThemeProvider found in context');
    return notifier!;
  }
}

/// Internal widget that rebuilds when [AppThemeNotifier] changes.
class _AppThemeBuilder extends StatefulWidget {
  final AppThemeNotifier notifier;
  final Widget Function(BuildContext context, AppThemeNotifier notifier)
  builder;

  const _AppThemeBuilder({required this.notifier, required this.builder});

  @override
  State<_AppThemeBuilder> createState() => _AppThemeBuilderState();
}

class _AppThemeBuilderState extends State<_AppThemeBuilder> {
  @override
  void initState() {
    super.initState();
    widget.notifier.addListener(_onThemeChanged);
  }

  @override
  void didUpdateWidget(_AppThemeBuilder oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.notifier != oldWidget.notifier) {
      oldWidget.notifier.removeListener(_onThemeChanged);
      widget.notifier.addListener(_onThemeChanged);
    }
  }

  @override
  void dispose() {
    widget.notifier.removeListener(_onThemeChanged);
    super.dispose();
  }

  void _onThemeChanged() {
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return widget.builder(context, widget.notifier);
  }
}

/// Manages theme token storage and server-side overrides.
///
/// The store maintains a current mode (e.g., "dark", "light") and a map
/// of overrides. All lookups check overrides first, then fall back
/// to the const lookup maps for the current mode.
class _TokenStore {
  String _mode;
  Map<String, dynamic> _overrides = const {};

  _TokenStore({required String mode}) : _mode = mode;

  String get mode => _mode;
  set mode(String value) => _mode = value;

  Map<String, dynamic> get overrides => _overrides;

  void setOverrides(Map<String, dynamic> overrides) {
    _overrides = Map.unmodifiable(overrides);
  }

  void clearOverrides() {
    _overrides = const {};
  }

  /// Looks up a color by full group path and token name.
  ///
  /// Returns the override if one exists for the full path, otherwise
  /// returns the value from the const map for the current mode.
  Color? color(String groupPath, String token) {
    // Check override first using the full token path.
    final path = "$_mode.color.$groupPath.$token";
    final override = _overrides[path];
    if (override is Color) return override;

    // Lookup in the appropriate mode map.
    final pascalPath = groupPath.split('.').map((s) => _pascalCase(s)).join();
    if (_mode == 'dark') {
      switch (pascalPath) {
        case "Action":
          return _darkColorAction[token];
        case "Brand":
          return _darkColorBrand[token];
        case "Canvas":
          return _darkColorCanvas[token];
        case "Feedback":
          return _darkColorFeedback[token];
        case "Foreground":
          return _darkColorForeground[token];
        case "Icon":
          return _darkColorIcon[token];
        case "Indicator":
          return _darkColorIndicator[token];
        case "Input":
          return _darkColorInput[token];
        case "Stroke":
          return _darkColorStroke[token];
        case "Surface":
          return _darkColorSurface[token];
      }
    } else {
      switch (pascalPath) {
        case "Action":
          return _lightColorAction[token];
        case "Brand":
          return _lightColorBrand[token];
        case "Canvas":
          return _lightColorCanvas[token];
        case "Feedback":
          return _lightColorFeedback[token];
        case "Foreground":
          return _lightColorForeground[token];
        case "Icon":
          return _lightColorIcon[token];
        case "Indicator":
          return _lightColorIndicator[token];
        case "Input":
          return _lightColorInput[token];
        case "Stroke":
          return _lightColorStroke[token];
        case "Surface":
          return _lightColorSurface[token];
      }
    }
    return null;
  }

  /// Looks up a size dimension by full group path and token name.
  ///
  /// Returns the override if one exists, otherwise returns the value
  /// from the const map for the current mode.
  double? size(String groupPath, String token) {
    final path = "$_mode.sizes.$groupPath.$token";
    final override = _overrides[path];
    if (override is double) return override;

    final pascalPath = groupPath.split('.').map((s) => _pascalCase(s)).join();
    if (_mode == 'dark') {
      switch (pascalPath) {
        case "Blur":
          return _darkSizeBlur[token];
        case "Font":
          return _darkSizeFont[token];
        case "Icon":
          return _darkSizeIcon[token];
        case "Motion":
          return _darkSizeMotion[token];
        case "Padding":
          return _darkSizePadding[token];
        case "Radius":
          return _darkSizeRadius[token];
        case "Spacing":
          return _darkSizeSpacing[token];
      }
    } else {
      switch (pascalPath) {
        case "Blur":
          return _lightSizeBlur[token];
        case "Font":
          return _lightSizeFont[token];
        case "Icon":
          return _lightSizeIcon[token];
        case "Motion":
          return _lightSizeMotion[token];
        case "Padding":
          return _lightSizePadding[token];
        case "Radius":
          return _lightSizeRadius[token];
        case "Spacing":
          return _lightSizeSpacing[token];
      }
    }
    return null;
  }

  /// Looks up a text style by full group path and token name.
  ///
  /// Returns the override if one exists, otherwise returns the style
  /// from the const map for the current mode.
  TextStyle? textStyle(String groupPath, String token) {
    final path = "$_mode.typography.$groupPath.$token";
    final override = _overrides[path];
    if (override is TextStyle) return override;

    final pascalPath = groupPath.split('.').map((s) => _pascalCase(s)).join();
    if (_mode == 'dark') {
      switch (pascalPath) {
        case "Body":
          return _darkTypographyBody[token];
        case "Caption":
          return _darkTypographyCaption[token];
        case "Display":
          return _darkTypographyDisplay[token];
        case "Headline":
          return _darkTypographyHeadline[token];
        case "Label":
          return _darkTypographyLabel[token];
        case "Title":
          return _darkTypographyTitle[token];
      }
    } else {
      switch (pascalPath) {
        case "Body":
          return _lightTypographyBody[token];
        case "Caption":
          return _lightTypographyCaption[token];
        case "Display":
          return _lightTypographyDisplay[token];
        case "Headline":
          return _lightTypographyHeadline[token];
        case "Label":
          return _lightTypographyLabel[token];
        case "Title":
          return _lightTypographyTitle[token];
      }
    }
    return null;
  }

  /// Converts a string to PascalCase.
  String _pascalCase(String input) {
    if (input.isEmpty) return input;
    return input[0].toUpperCase() + input.substring(1);
  }
}

/// Extension methods on [BuildContext] for convenient theme access.
extension AppThemeContextExtensions on BuildContext {
  /// Retrieves the [AppTheme] from the current context.
  ///
  /// This is equivalent to `Theme.of(context).extension<AppTheme>()!` but
  /// provides a more concise syntax: `context.theme`.
  AppTheme get theme {
    return Theme.of(this).extension<AppTheme>()!;
  }

  /// Retrieves the [AppThemeNotifier] from the current context.
  ///
  /// This is equivalent to `AppThemeProvider.of(context)` but
  /// provides a more concise syntax: `context.themeNotifier`.
  AppThemeNotifier get themeNotifier {
    return AppThemeProvider.of(this);
  }

  /// Retrieves the [AppThemeNotifier] from the current context (nullable).
  ///
  /// Returns null if no [AppThemeProvider] is found in the ancestry.
  AppThemeNotifier? get themeNotifierMaybe {
    return AppThemeProvider.maybeOf(this);
  }
}

/// Provides access to all color category groups.
class _ThemeColors {
  final _TokenStore _store;
  const _ThemeColors(this._store);

  /// Colors for interactive / tappable elements — buttons, chips, FABs,
  /// toggles
  _ActionColors get action => _ActionColors(_store);

  /// Brand identity colors — the primary product accent
  _BrandColors get brand => _BrandColors(_store);

  /// Screen / page background layers — the painted surface beneath all
  /// content
  _CanvasColors get canvas => _CanvasColors(_store);

  /// UI state signal colors — communicates the result of an action or system
  /// condition
  _FeedbackColors get feedback => _FeedbackColors(_store);

  /// Text colors rendered on top of any surface
  _ForegroundColors get foreground => _ForegroundColors(_store);

  /// Icon / glyph colors — parallel to foreground but scoped to iconography
  _IconColors get icon => _IconColors(_store);

  /// Status indicator colors — badges, chips, tags, and lifecycle pills
  _IndicatorColors get indicator => _IndicatorColors(_store);

  /// Colors scoped to form controls — text fields, selects, textareas
  _InputColors get input => _InputColors(_store);

  /// Border, divider, and outline colors
  _StrokeColors get stroke => _StrokeColors(_store);

  /// Elevated container colors — cards, sheets, and raised panels
  _SurfaceColors get surface => _SurfaceColors(_store);
}

/// Provides access to all size category groups.
class _ThemeSizes {
  final _TokenStore _store;
  const _ThemeSizes(this._store);

  /// Blur intensity scale for backdrop effects
  _BlurSizes get blur => _BlurSizes(_store);

  /// Font size scale for typography
  _FontSizes get font => _FontSizes(_store);

  /// Icon size scale for glyphs and symbols
  _IconSizes get icon => _IconSizes(_store);

  /// Motion duration scale for animations and transitions
  _MotionSizes get motion => _MotionSizes(_store);

  /// Padding scale for internal component spacing
  _PaddingSizes get padding => _PaddingSizes(_store);

  /// Border radius scale for rounding corners
  _RadiusSizes get radius => _RadiusSizes(_store);

  /// Spacing scale for gaps between components and layout
  _SpacingSizes get spacing => _SpacingSizes(_store);
}

/// Provides access to all typography category groups.
class _ThemeTypography {
  final _TokenStore _store;
  const _ThemeTypography(this._store);

  /// Body typography scale for paragraphs and content text
  _BodyTypography get body => _BodyTypography(_store);

  /// Caption typography scale for small helper text and metadata
  _CaptionTypography get caption => _CaptionTypography(_store);

  /// Display typography scale for large headlines and hero text
  _DisplayTypography get display => _DisplayTypography(_store);

  /// Headline typography scale for section headings
  _HeadlineTypography get headline => _HeadlineTypography(_store);

  /// Label typography scale for form labels and captions
  _LabelTypography get label => _LabelTypography(_store);

  /// Title typography scale for card and component titles
  _TitleTypography get title => _TitleTypography(_store);
}

/// Colors for interactive / tappable elements — buttons, chips, FABs,
/// toggles
class _ActionColors {
  final _TokenStore _store;

  const _ActionColors(this._store);

  /// Disabled button background
  Color get disabled => _store.color('action', 'disabled')!;

  /// Error/destructive filled button
  Color get filledDanger => _store.color('action', 'filledDanger')!;

  /// Primary filled button hover state
  Color get filledHover => _store.color('action', 'filledHover')!;

  /// Primary filled button active state - deep blue
  Color get filledPrimary => _store.color('action', 'filledPrimary')!;

  /// Secondary button hover state
  Color get ghostHover => _store.color('action', 'ghostHover')!;

  /// Secondary button active state - lighter coral
  Color get ghostPrimary => _store.color('action', 'ghostPrimary')!;

  /// Outlined button border color
  Color get outline => _store.color('action', 'outline')!;
}

/// Brand identity colors — the primary product accent
class _BrandColors {
  final _TokenStore _store;

  const _BrandColors(this._store);

  /// Surface color for primary tinted backgrounds - dark
  Color get container => _store.color('brand', 'container')!;

  /// Primary brand color - deep blue for dark mode
  Color get primary => _store.color('brand', 'primary')!;
}

/// Screen / page background layers — the painted surface beneath all content
class _CanvasColors {
  final _TokenStore _store;

  const _CanvasColors(this._store);

  /// Primary tinted background - dark blue
  Color get brand => _store.color('canvas', 'brand')!;

  /// Error state surface background - dark red tint
  Color get error => _store.color('canvas', 'error')!;

  /// Info state surface background - dark blue tint
  Color get info => _store.color('canvas', 'info')!;

  /// Generic gray background - dark
  Color get neutral => _store.color('canvas', 'neutral')!;

  /// Main scaffold background - very dark
  Color get primary => _store.color('canvas', 'primary')!;

  /// Secondary surface - dark gray
  Color get secondary => _store.color('canvas', 'secondary')!;

  /// Success state surface background - dark green tint
  Color get success => _store.color('canvas', 'success')!;

  /// Tertiary surface - medium dark
  Color get tertiary => _store.color('canvas', 'tertiary')!;

  /// Warning state surface background - dark orange tint
  Color get warning => _store.color('canvas', 'warning')!;
}

/// UI state signal colors — communicates the result of an action or system
/// condition
class _FeedbackColors {
  final _TokenStore _store;

  const _FeedbackColors(this._store);

  /// Danger/error status color - light red
  Color get danger => _store.color('feedback', 'danger')!;

  /// Info status color - light blue
  Color get info => _store.color('feedback', 'info')!;

  /// Success status color - light emerald
  Color get success => _store.color('feedback', 'success')!;

  /// Warning status color - light amber
  Color get warning => _store.color('feedback', 'warning')!;
}

/// Text colors rendered on top of any surface
class _ForegroundColors {
  final _TokenStore _store;

  const _ForegroundColors(this._store);

  /// Body text color - medium gray
  Color get body => _store.color('foreground', 'body')!;

  /// Disabled text color - darker gray
  Color get disabled => _store.color('foreground', 'disabled')!;

  /// Error state text color - lighter red
  Color get error => _store.color('foreground', 'error')!;

  /// Info state text color - lighter blue
  Color get info => _store.color('foreground', 'info')!;

  /// Text on filled/colored backgrounds
  Color get inverse => _store.color('foreground', 'inverse')!;

  /// Placeholder text color
  Color get placeholder => _store.color('foreground', 'placeholder')!;

  /// Primary text color - white for dark backgrounds
  Color get primary => _store.color('foreground', 'primary')!;

  /// Secondary text color - light gray
  Color get subtle => _store.color('foreground', 'subtle')!;

  /// Success state text color - lighter green
  Color get success => _store.color('foreground', 'success')!;

  /// Title text color - white
  Color get title => _store.color('foreground', 'title')!;

  /// Warning state text color - lighter orange
  Color get warning => _store.color('foreground', 'warning')!;
}

/// Icon / glyph colors — parallel to foreground but scoped to iconography
class _IconColors {
  final _TokenStore _store;

  const _IconColors(this._store);

  /// Icon color for body text areas
  Color get body => _store.color('icon', 'body')!;

  /// Disabled icon color
  Color get disabled => _store.color('icon', 'disabled')!;

  /// Error icon color
  Color get error => _store.color('icon', 'error')!;

  /// Info icon color
  Color get info => _store.color('icon', 'info')!;

  /// Icon on filled backgrounds
  Color get inverse => _store.color('icon', 'inverse')!;

  /// Primary icon color - white
  Color get primary => _store.color('icon', 'primary')!;

  /// Secondary/accent icon color - lighter coral
  Color get subtle => _store.color('icon', 'subtle')!;

  /// Success icon color
  Color get success => _store.color('icon', 'success')!;

  /// Icon color for titles
  Color get title => _store.color('icon', 'title')!;

  /// Warning icon color
  Color get warning => _store.color('icon', 'warning')!;
}

/// Status indicator colors — badges, chips, tags, and lifecycle pills
class _IndicatorColors {
  final _TokenStore _store;

  const _IndicatorColors(this._store);

  /// Hired status badge - light green
  Color get hired => _store.color('indicator', 'hired')!;

  /// In review status badge - light blue
  Color get inReview => _store.color('indicator', 'inReview')!;

  /// Interview status badge - light purple
  Color get interview => _store.color('indicator', 'interview')!;

  /// Offer status badge - light green
  Color get offer => _store.color('indicator', 'offer')!;

  /// Pending status badge - light amber
  Color get pending => _store.color('indicator', 'pending')!;

  /// Rejected status badge - light red
  Color get rejected => _store.color('indicator', 'rejected')!;

  /// Urgent badge color - light red
  Color get urgent => _store.color('indicator', 'urgent')!;
}

/// Colors scoped to form controls — text fields, selects, textareas
class _InputColors {
  final _TokenStore _store;

  const _InputColors(this._store);

  /// TextField disabled color
  Color get disabled => _store.color('input', 'disabled')!;

  /// TextField error state color
  Color get error => _store.color('input', 'error')!;

  /// TextField background color - dark gray
  Color get fill => _store.color('input', 'fill')!;

  /// TextField focus border color - blue
  Color get focus => _store.color('input', 'focus')!;

  /// TextField label color - light gray
  Color get label => _store.color('input', 'label')!;

  /// TextField border color
  Color get outline => _store.color('input', 'outline')!;

  /// TextField placeholder color
  Color get placeholder => _store.color('input', 'placeholder')!;

  /// TextField primary color - white
  Color get primary => _store.color('input', 'primary')!;

  /// TextField input text color - white
  Color get value => _store.color('input', 'value')!;
}

/// Border, divider, and outline colors
class _StrokeColors {
  final _TokenStore _store;

  const _StrokeColors(this._store);

  /// Divider line color - dark
  Color get divider => _store.color('stroke', 'divider')!;

  /// Primary stroke/border color - dark
  Color get emphasis => _store.color('stroke', 'emphasis')!;

  /// Error outline/border color - light red
  Color get error => _store.color('stroke', 'error')!;

  /// Inverse stroke for light backgrounds
  Color get inverse => _store.color('stroke', 'inverse')!;

  /// Default border stroke - dark
  Color get primary => _store.color('stroke', 'primary')!;
}

/// Elevated container colors — cards, sheets, and raised panels
class _SurfaceColors {
  final _TokenStore _store;

  const _SurfaceColors(this._store);

  /// Card background color - dark surface
  Color get card => _store.color('surface', 'card')!;
}

/// Blur intensity scale for backdrop effects
class _BlurSizes {
  final _TokenStore _store;

  const _BlurSizes(this._store);

  /// Large blur - 16px
  double get lg => _store.size('blur', 'lg') ?? 16.0;

  /// Medium blur - 8px
  double get md => _store.size('blur', 'md') ?? 8.0;

  /// Small blur - 4px
  double get sm => _store.size('blur', 'sm') ?? 4.0;

  /// Extra large blur - 24px
  double get xl => _store.size('blur', 'xl') ?? 24.0;

  /// Extra small blur - 2px
  double get xs => _store.size('blur', 'xs') ?? 2.0;
}

/// Font size scale for typography
class _FontSizes {
  final _TokenStore _store;

  const _FontSizes(this._store);

  /// Large font (body large, title medium)
  double get lg => _store.size('font', 'lg') ?? 16.0;

  /// Medium font (body medium)
  double get md => _store.size('font', 'md') ?? 14.0;

  /// Small font (caption)
  double get sm => _store.size('font', 'sm') ?? 12.0;

  /// 2x large font (display medium)
  double get x2l => _store.size('font', 'x2l') ?? 24.0;

  /// 3x large font (display large)
  double get x3l => _store.size('font', 'x3l') ?? 32.0;

  /// Extra large font (title large)
  double get xl => _store.size('font', 'xl') ?? 20.0;

  /// Extra small font - 10px
  double get xs => _store.size('font', 'xs') ?? 10.0;
}

/// Icon size scale for glyphs and symbols
class _IconSizes {
  final _TokenStore _store;

  const _IconSizes(this._store);

  /// Large icon - 24px
  double get lg => _store.size('icon', 'lg') ?? 24.0;

  /// Medium icon - 20px
  double get md => _store.size('icon', 'md') ?? 20.0;

  /// Small icon - 16px
  double get sm => _store.size('icon', 'sm') ?? 16.0;

  /// 2x large icon - 40px
  double get x2l => _store.size('icon', 'x2l') ?? 40.0;

  /// 3x large icon - 48px
  double get x3l => _store.size('icon', 'x3l') ?? 48.0;

  /// Extra large icon - 32px
  double get xl => _store.size('icon', 'xl') ?? 32.0;

  /// Extra small icon - 12px
  double get xs => _store.size('icon', 'xs') ?? 12.0;
}

/// Motion duration scale for animations and transitions
class _MotionSizes {
  final _TokenStore _store;

  const _MotionSizes(this._store);

  /// Standard duration - 300ms
  double get lg => _store.size('motion', 'lg') ?? 300.0;

  /// Medium duration - 200ms
  double get md => _store.size('motion', 'md') ?? 200.0;

  /// Short duration - 100ms
  double get sm => _store.size('motion', 'sm') ?? 100.0;

  /// Long duration - 500ms
  double get xl => _store.size('motion', 'xl') ?? 500.0;

  /// Extra short duration - 50ms
  double get xs => _store.size('motion', 'xs') ?? 50.0;
}

/// Padding scale for internal component spacing
class _PaddingSizes {
  final _TokenStore _store;

  const _PaddingSizes(this._store);

  /// Large padding - 16px
  double get lg => _store.size('padding', 'lg') ?? 16.0;

  /// Medium padding - 12px
  double get md => _store.size('padding', 'md') ?? 12.0;

  /// Small padding - 8px
  double get sm => _store.size('padding', 'sm') ?? 8.0;

  /// 2x large padding - 24px
  double get x2l => _store.size('padding', 'x2l') ?? 24.0;

  /// 3x large padding - 32px
  double get x3l => _store.size('padding', 'x3l') ?? 32.0;

  /// 4x large padding - 40px
  double get x4l => _store.size('padding', 'x4l') ?? 40.0;

  /// 5x large padding - 48px
  double get x5l => _store.size('padding', 'x5l') ?? 48.0;

  /// 6x large padding - 64px
  double get x6l => _store.size('padding', 'x6l') ?? 64.0;

  /// 7x large padding - 80px
  double get x7l => _store.size('padding', 'x7l') ?? 80.0;

  /// Extra large padding - 20px
  double get xl => _store.size('padding', 'xl') ?? 20.0;

  /// Extra small padding - 4px
  double get xs => _store.size('padding', 'xs') ?? 4.0;
}

/// Border radius scale for rounding corners
class _RadiusSizes {
  final _TokenStore _store;

  const _RadiusSizes(this._store);

  /// Large radius - 12px
  double get lg => _store.size('radius', 'lg') ?? 12.0;

  /// Medium radius - 8px
  double get md => _store.size('radius', 'md') ?? 8.0;

  /// Pill/fully rounded radius
  double get pill => _store.size('radius', 'pill') ?? 9999.0;

  /// Small radius - 6px
  double get sm => _store.size('radius', 'sm') ?? 6.0;

  /// 2x large radius - 20px
  double get x2l => _store.size('radius', 'x2l') ?? 20.0;

  /// 3x large radius - 24px
  double get x3l => _store.size('radius', 'x3l') ?? 24.0;

  /// 4x large radius - 32px
  double get x4l => _store.size('radius', 'x4l') ?? 32.0;

  /// Extra large radius (cards)
  double get xl => _store.size('radius', 'xl') ?? 16.0;

  /// Extra small radius - 4px
  double get xs => _store.size('radius', 'xs') ?? 4.0;
}

/// Spacing scale for gaps between components and layout
class _SpacingSizes {
  final _TokenStore _store;

  const _SpacingSizes(this._store);

  /// Large spacing - 16px
  double get lg => _store.size('spacing', 'lg') ?? 16.0;

  /// Medium spacing - 12px
  double get md => _store.size('spacing', 'md') ?? 12.0;

  /// Small spacing - 8px
  double get sm => _store.size('spacing', 'sm') ?? 8.0;

  /// 2x large spacing - 24px
  double get x2l => _store.size('spacing', 'x2l') ?? 24.0;

  /// 3x large spacing - 32px
  double get x3l => _store.size('spacing', 'x3l') ?? 32.0;

  /// 4x large spacing - 40px
  double get x4l => _store.size('spacing', 'x4l') ?? 40.0;

  /// 5x large spacing - 48px
  double get x5l => _store.size('spacing', 'x5l') ?? 48.0;

  /// 6x large spacing - 64px
  double get x6l => _store.size('spacing', 'x6l') ?? 64.0;

  /// 7x large spacing - 80px
  double get x7l => _store.size('spacing', 'x7l') ?? 80.0;

  /// Extra large spacing - 20px
  double get xl => _store.size('spacing', 'xl') ?? 20.0;

  /// Extra small spacing - 4px
  double get xs => _store.size('spacing', 'xs') ?? 4.0;
}

/// Body typography scale for paragraphs and content text
class _BodyTypography {
  final _TokenStore _store;

  const _BodyTypography(this._store);

  /// Body - Black - Maximum weight for maximum impact
  TextStyle get black =>
      _store.textStyle('body', 'black') ??
      TextStyle(
        fontSize: 16,
        fontWeight: FontWeight.w900,
        height: 1.5,
        fontFamily: 'Inter',
      );

  /// Body - Bold - Strong emphasis for headings and key text
  TextStyle get bold =>
      _store.textStyle('body', 'bold') ??
      TextStyle(
        fontSize: 16,
        fontWeight: FontWeight.w700,
        height: 1.5,
        fontFamily: 'Inter',
      );

  /// Body - Extra bold - Heavy emphasis for prominent text
  TextStyle get extraBold =>
      _store.textStyle('body', 'extraBold') ??
      TextStyle(
        fontSize: 16,
        fontWeight: FontWeight.w800,
        height: 1.5,
        fontFamily: 'Inter',
      );

  /// Body - Extra light - Very light weight for elegant display text
  TextStyle get extraLight =>
      _store.textStyle('body', 'extraLight') ??
      TextStyle(
        fontSize: 16,
        fontWeight: FontWeight.w200,
        height: 1.5,
        fontFamily: 'Inter',
      );

  /// Body - Light - Soft weight for refined display text
  TextStyle get light =>
      _store.textStyle('body', 'light') ??
      TextStyle(
        fontSize: 16,
        fontWeight: FontWeight.w300,
        height: 1.5,
        fontFamily: 'Inter',
      );

  /// Body - Medium - Slightly emphasized text for UI elements
  TextStyle get medium =>
      _store.textStyle('body', 'medium') ??
      TextStyle(
        fontSize: 14,
        fontWeight: FontWeight.w500,
        height: 1.5,
        fontFamily: 'Inter',
      );

  /// Body - Regular - Normal weight for standard body text
  TextStyle get regular =>
      _store.textStyle('body', 'regular') ??
      TextStyle(
        fontSize: 16,
        fontWeight: FontWeight.w400,
        height: 1.5,
        fontFamily: 'Inter',
      );

  /// Body - Semi-bold - Moderate emphasis for subheadings
  TextStyle get semiBold =>
      _store.textStyle('body', 'semiBold') ??
      TextStyle(
        fontSize: 16,
        fontWeight: FontWeight.w600,
        height: 1.5,
        fontFamily: 'Inter',
      );

  /// Body - Thin - Delicate, minimal weight for subtle display text
  TextStyle get thin =>
      _store.textStyle('body', 'thin') ??
      TextStyle(
        fontSize: 16,
        fontWeight: FontWeight.w100,
        height: 1.5,
        fontFamily: 'Inter',
      );
}

/// Caption typography scale for small helper text and metadata
class _CaptionTypography {
  final _TokenStore _store;

  const _CaptionTypography(this._store);

  /// Caption - Black - Maximum weight for maximum impact
  TextStyle get black =>
      _store.textStyle('caption', 'black') ??
      TextStyle(
        fontSize: 12,
        fontWeight: FontWeight.w900,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Caption - Bold - Strong emphasis for headings and key text
  TextStyle get bold =>
      _store.textStyle('caption', 'bold') ??
      TextStyle(
        fontSize: 12,
        fontWeight: FontWeight.w700,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Caption - Extra bold - Heavy emphasis for prominent text
  TextStyle get extraBold =>
      _store.textStyle('caption', 'extraBold') ??
      TextStyle(
        fontSize: 12,
        fontWeight: FontWeight.w800,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Caption - Extra light - Very light weight for elegant display text
  TextStyle get extraLight =>
      _store.textStyle('caption', 'extraLight') ??
      TextStyle(
        fontSize: 12,
        fontWeight: FontWeight.w200,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Caption - Light - Soft weight for refined display text
  TextStyle get light =>
      _store.textStyle('caption', 'light') ??
      TextStyle(
        fontSize: 12,
        fontWeight: FontWeight.w300,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Caption - Medium - Slightly emphasized text for UI elements
  TextStyle get medium =>
      _store.textStyle('caption', 'medium') ??
      TextStyle(
        fontSize: 12,
        fontWeight: FontWeight.w500,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Caption - Regular - Normal weight for standard body text
  TextStyle get regular =>
      _store.textStyle('caption', 'regular') ??
      TextStyle(
        fontSize: 12,
        fontWeight: FontWeight.w400,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Caption - Semi-bold - Moderate emphasis for subheadings
  TextStyle get semiBold =>
      _store.textStyle('caption', 'semiBold') ??
      TextStyle(
        fontSize: 12,
        fontWeight: FontWeight.w600,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Caption - Thin - Delicate, minimal weight for subtle display text
  TextStyle get thin =>
      _store.textStyle('caption', 'thin') ??
      TextStyle(
        fontSize: 12,
        fontWeight: FontWeight.w100,
        height: 1.4,
        fontFamily: 'Inter',
      );
}

/// Display typography scale for large headlines and hero text
class _DisplayTypography {
  final _TokenStore _store;

  const _DisplayTypography(this._store);

  /// Display - Black - Maximum weight for maximum impact
  TextStyle get black =>
      _store.textStyle('display', 'black') ??
      TextStyle(
        fontSize: 32,
        fontWeight: FontWeight.w900,
        height: 1.2,
        fontFamily: 'Inter',
      );

  /// Display - Bold - Strong emphasis for headings and key text
  TextStyle get bold =>
      _store.textStyle('display', 'bold') ??
      TextStyle(
        fontSize: 32,
        fontWeight: FontWeight.w700,
        height: 1.2,
        fontFamily: 'Inter',
      );

  /// Display - Extra bold - Heavy emphasis for prominent text
  TextStyle get extraBold =>
      _store.textStyle('display', 'extraBold') ??
      TextStyle(
        fontSize: 32,
        fontWeight: FontWeight.w800,
        height: 1.2,
        fontFamily: 'Inter',
      );

  /// Display - Extra light - Very light weight for elegant display text
  TextStyle get extraLight =>
      _store.textStyle('display', 'extraLight') ??
      TextStyle(
        fontSize: 32,
        fontWeight: FontWeight.w200,
        height: 1.2,
        fontFamily: 'Inter',
      );

  /// Display - Light - Soft weight for refined display text
  TextStyle get light =>
      _store.textStyle('display', 'light') ??
      TextStyle(
        fontSize: 32,
        fontWeight: FontWeight.w300,
        height: 1.2,
        fontFamily: 'Inter',
      );

  /// Display - Medium - Slightly emphasized text for UI elements
  TextStyle get medium =>
      _store.textStyle('display', 'medium') ??
      TextStyle(
        fontSize: 32,
        fontWeight: FontWeight.w500,
        height: 1.2,
        fontFamily: 'Inter',
      );

  /// Display - Regular - Normal weight for standard body text
  TextStyle get regular =>
      _store.textStyle('display', 'regular') ??
      TextStyle(
        fontSize: 32,
        fontWeight: FontWeight.w400,
        height: 1.2,
        fontFamily: 'Inter',
      );

  /// Display - Semi-bold - Moderate emphasis for subheadings
  TextStyle get semiBold =>
      _store.textStyle('display', 'semiBold') ??
      TextStyle(
        fontSize: 32,
        fontWeight: FontWeight.w600,
        height: 1.2,
        fontFamily: 'Inter',
      );

  /// Display - Thin - Delicate, minimal weight for subtle display text
  TextStyle get thin =>
      _store.textStyle('display', 'thin') ??
      TextStyle(
        fontSize: 32,
        fontWeight: FontWeight.w100,
        height: 1.2,
        fontFamily: 'Inter',
      );
}

/// Headline typography scale for section headings
class _HeadlineTypography {
  final _TokenStore _store;

  const _HeadlineTypography(this._store);

  /// Headline - Black - Maximum weight for maximum impact
  TextStyle get black =>
      _store.textStyle('headline', 'black') ??
      TextStyle(
        fontSize: 28,
        fontWeight: FontWeight.w900,
        height: 1.3,
        fontFamily: 'Inter',
      );

  /// Headline - Bold - Strong emphasis for headings and key text
  TextStyle get bold =>
      _store.textStyle('headline', 'bold') ??
      TextStyle(
        fontSize: 28,
        fontWeight: FontWeight.w700,
        height: 1.3,
        fontFamily: 'Inter',
      );

  /// Headline - Extra bold - Heavy emphasis for prominent text
  TextStyle get extraBold =>
      _store.textStyle('headline', 'extraBold') ??
      TextStyle(
        fontSize: 28,
        fontWeight: FontWeight.w800,
        height: 1.3,
        fontFamily: 'Inter',
      );

  /// Headline - Extra light - Very light weight for elegant display text
  TextStyle get extraLight =>
      _store.textStyle('headline', 'extraLight') ??
      TextStyle(
        fontSize: 28,
        fontWeight: FontWeight.w200,
        height: 1.3,
        fontFamily: 'Inter',
      );

  /// Headline - Light - Soft weight for refined display text
  TextStyle get light =>
      _store.textStyle('headline', 'light') ??
      TextStyle(
        fontSize: 28,
        fontWeight: FontWeight.w300,
        height: 1.3,
        fontFamily: 'Inter',
      );

  /// Headline - Medium - Slightly emphasized text for UI elements
  TextStyle get medium =>
      _store.textStyle('headline', 'medium') ??
      TextStyle(
        fontSize: 28,
        fontWeight: FontWeight.w500,
        height: 1.3,
        fontFamily: 'Inter',
      );

  /// Headline - Regular - Normal weight for standard body text
  TextStyle get regular =>
      _store.textStyle('headline', 'regular') ??
      TextStyle(
        fontSize: 28,
        fontWeight: FontWeight.w400,
        height: 1.3,
        fontFamily: 'Inter',
      );

  /// Headline - Semi-bold - Moderate emphasis for subheadings
  TextStyle get semiBold =>
      _store.textStyle('headline', 'semiBold') ??
      TextStyle(
        fontSize: 28,
        fontWeight: FontWeight.w600,
        height: 1.3,
        fontFamily: 'Inter',
      );

  /// Headline - Thin - Delicate, minimal weight for subtle display text
  TextStyle get thin =>
      _store.textStyle('headline', 'thin') ??
      TextStyle(
        fontSize: 28,
        fontWeight: FontWeight.w100,
        height: 1.3,
        fontFamily: 'Inter',
      );
}

/// Label typography scale for form labels and captions
class _LabelTypography {
  final _TokenStore _store;

  const _LabelTypography(this._store);

  /// Label - Black - Maximum weight for maximum impact
  TextStyle get black =>
      _store.textStyle('label', 'black') ??
      TextStyle(
        fontSize: 14,
        fontWeight: FontWeight.w900,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Label - Bold - Strong emphasis for headings and key text
  TextStyle get bold =>
      _store.textStyle('label', 'bold') ??
      TextStyle(
        fontSize: 14,
        fontWeight: FontWeight.w700,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Label - Extra bold - Heavy emphasis for prominent text
  TextStyle get extraBold =>
      _store.textStyle('label', 'extraBold') ??
      TextStyle(
        fontSize: 14,
        fontWeight: FontWeight.w800,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Label - Extra light - Very light weight for elegant display text
  TextStyle get extraLight =>
      _store.textStyle('label', 'extraLight') ??
      TextStyle(
        fontSize: 14,
        fontWeight: FontWeight.w200,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Label - Light - Soft weight for refined display text
  TextStyle get light =>
      _store.textStyle('label', 'light') ??
      TextStyle(
        fontSize: 14,
        fontWeight: FontWeight.w300,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Label - Medium - Slightly emphasized text for UI elements
  TextStyle get medium =>
      _store.textStyle('label', 'medium') ??
      TextStyle(
        fontSize: 12,
        fontWeight: FontWeight.w500,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Label - Regular - Normal weight for standard body text
  TextStyle get regular =>
      _store.textStyle('label', 'regular') ??
      TextStyle(
        fontSize: 14,
        fontWeight: FontWeight.w400,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Label - Semi-bold - Moderate emphasis for subheadings
  TextStyle get semiBold =>
      _store.textStyle('label', 'semiBold') ??
      TextStyle(
        fontSize: 14,
        fontWeight: FontWeight.w600,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Label - Thin - Delicate, minimal weight for subtle display text
  TextStyle get thin =>
      _store.textStyle('label', 'thin') ??
      TextStyle(
        fontSize: 14,
        fontWeight: FontWeight.w100,
        height: 1.4,
        fontFamily: 'Inter',
      );
}

/// Title typography scale for card and component titles
class _TitleTypography {
  final _TokenStore _store;

  const _TitleTypography(this._store);

  /// Title - Black - Maximum weight for maximum impact
  TextStyle get black =>
      _store.textStyle('title', 'black') ??
      TextStyle(
        fontSize: 20,
        fontWeight: FontWeight.w900,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Title - Bold - Strong emphasis for headings and key text
  TextStyle get bold =>
      _store.textStyle('title', 'bold') ??
      TextStyle(
        fontSize: 20,
        fontWeight: FontWeight.w700,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Title - Extra bold - Heavy emphasis for prominent text
  TextStyle get extraBold =>
      _store.textStyle('title', 'extraBold') ??
      TextStyle(
        fontSize: 20,
        fontWeight: FontWeight.w800,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Title - Extra light - Very light weight for elegant display text
  TextStyle get extraLight =>
      _store.textStyle('title', 'extraLight') ??
      TextStyle(
        fontSize: 20,
        fontWeight: FontWeight.w200,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Title - Light - Soft weight for refined display text
  TextStyle get light =>
      _store.textStyle('title', 'light') ??
      TextStyle(
        fontSize: 20,
        fontWeight: FontWeight.w300,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Title - Medium - Slightly emphasized text for UI elements
  TextStyle get medium =>
      _store.textStyle('title', 'medium') ??
      TextStyle(
        fontSize: 16,
        fontWeight: FontWeight.w500,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Title - Regular - Normal weight for standard body text
  TextStyle get regular =>
      _store.textStyle('title', 'regular') ??
      TextStyle(
        fontSize: 20,
        fontWeight: FontWeight.w400,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Title - Semi-bold - Moderate emphasis for subheadings
  TextStyle get semiBold =>
      _store.textStyle('title', 'semiBold') ??
      TextStyle(
        fontSize: 20,
        fontWeight: FontWeight.w600,
        height: 1.4,
        fontFamily: 'Inter',
      );

  /// Title - Thin - Delicate, minimal weight for subtle display text
  TextStyle get thin =>
      _store.textStyle('title', 'thin') ??
      TextStyle(
        fontSize: 20,
        fontWeight: FontWeight.w100,
        height: 1.4,
        fontFamily: 'Inter',
      );
}

const Map<String, Color> _darkColorAction = <String, Color>{
  'filledPrimary': Color(0xFF2D3A8C),
  'filledHover': Color(0xFF3D4A9C),
  'ghostPrimary': Color(0xFFFF6B7A),
  'ghostHover': Color(0xFFFF8B9A),
  'outline': Color(0xFFFFFFFF),
  'disabled': Color(0xFFE5E7EB),
  'filledDanger': Color(0xFFEF4444),
};

const Map<String, Color> _darkColorBrand = <String, Color>{
  'primary': Color(0xFF2D3A8C),
  'container': Color(0xFF1E1E2E),
};

const Map<String, Color> _darkColorCanvas = <String, Color>{
  'primary': Color(0xFF121212),
  'secondary': Color(0xFF1E1E1E),
  'tertiary': Color(0xFF2A2A2A),
  'error': Color(0xFF3A1E1E),
  'info': Color(0xFF1E2A3A),
  'warning': Color(0xFF3A2E1E),
  'success': Color(0xFF1E3A2E),
  'neutral': Color(0xFF2A2A2A),
  'brand': Color(0xFF2D3A8C),
};

const Map<String, Color> _darkColorFeedback = <String, Color>{
  'warning': Color(0xFFFFA500),
  'danger': Color(0xFFEF4444),
  'success': Color(0xFF10B981),
  'info': Color(0xFF4A90E2),
};

const Map<String, Color> _darkColorForeground = <String, Color>{
  'primary': Color(0xFFFFFFFF),
  'subtle': Color(0xFFB0B0B0),
  'title': Color(0xFFFFFFFF),
  'body': Color(0xFF808080),
  'disabled': Color(0xFF9CA3AF),
  'placeholder': Color(0xFF9CA3AF),
  'inverse': Color(0xFFFFFFFF),
  'success': Color(0xFF10B981),
  'info': Color(0xFF4A90E2),
  'warning': Color(0xFFFFA500),
  'error': Color(0xFFEF4444),
};

const Map<String, Color> _darkColorIcon = <String, Color>{
  'primary': Color(0xFFFFFFFF),
  'subtle': Color(0xFFFF6B7A),
  'title': Color(0xFFFFFFFF),
  'body': Color(0xFF808080),
  'disabled': Color(0xFF9CA3AF),
  'inverse': Color(0xFFFFFFFF),
  'success': Color(0xFF10B981),
  'info': Color(0xFF4A90E2),
  'warning': Color(0xFFFFA500),
  'error': Color(0xFFEF4444),
};

const Map<String, Color> _darkColorIndicator = <String, Color>{
  'urgent': Color(0xFFEF4444),
  'pending': Color(0xFFFFA500),
  'inReview': Color(0xFF4A90E2),
  'interview': Color(0xFFA78BFA),
  'offer': Color(0xFF10B981),
  'hired': Color(0xFF10B981),
  'rejected': Color(0xFFEF4444),
};

const Map<String, Color> _darkColorInput = <String, Color>{
  'primary': Color(0xFFFFFFFF),
  'label': Color(0xFFB0B0B0),
  'value': Color(0xFFFFFFFF),
  'placeholder': Color(0xFF9CA3AF),
  'disabled': Color(0xFF9CA3AF),
  'fill': Color(0xFF2A2A2A),
  'outline': Color(0xFFE5E7EB),
  'focus': Color(0xFF60A5FA),
  'error': Color(0xFFEF4444),
};

const Map<String, Color> _darkColorStroke = <String, Color>{
  'emphasis': Color(0xFF4A4A4A),
  'primary': Color(0xFFE5E7EB),
  'divider': Color(0xFFE5E7EB),
  'inverse': Color(0xFF1A1A2E),
  'error': Color(0xFFEF4444),
};

const Map<String, Color> _darkColorSurface = <String, Color>{
  'card': Color(0xFF1E1E1E),
};

const Map<String, double> _darkSizeBlur = <String, double>{
  'xs': 2.0,
  'sm': 4.0,
  'md': 8.0,
  'lg': 16.0,
  'xl': 24.0,
};

const Map<String, double> _darkSizeFont = <String, double>{
  'xs': 10.0,
  'sm': 12.0,
  'md': 14.0,
  'lg': 16.0,
  'xl': 20.0,
  'x2l': 24.0,
  'x3l': 32.0,
};

const Map<String, double> _darkSizeIcon = <String, double>{
  'xs': 12.0,
  'sm': 16.0,
  'md': 20.0,
  'lg': 24.0,
  'xl': 32.0,
  'x2l': 40.0,
  'x3l': 48.0,
};

const Map<String, double> _darkSizeMotion = <String, double>{
  'xs': 50.0,
  'sm': 100.0,
  'md': 200.0,
  'lg': 300.0,
  'xl': 500.0,
};

const Map<String, double> _darkSizePadding = <String, double>{
  'xs': 4.0,
  'sm': 8.0,
  'md': 12.0,
  'lg': 16.0,
  'xl': 20.0,
  'x2l': 24.0,
  'x3l': 32.0,
  'x4l': 40.0,
  'x5l': 48.0,
  'x6l': 64.0,
  'x7l': 80.0,
};

const Map<String, double> _darkSizeRadius = <String, double>{
  'xs': 4.0,
  'sm': 6.0,
  'md': 8.0,
  'lg': 12.0,
  'xl': 16.0,
  'x2l': 20.0,
  'x3l': 24.0,
  'x4l': 32.0,
  'pill': 9999.0,
};

const Map<String, double> _darkSizeSpacing = <String, double>{
  'xs': 4.0,
  'sm': 8.0,
  'md': 12.0,
  'lg': 16.0,
  'xl': 20.0,
  'x2l': 24.0,
  'x3l': 32.0,
  'x4l': 40.0,
  'x5l': 48.0,
  'x6l': 64.0,
  'x7l': 80.0,
};

const Map<String, TextStyle> _darkTypographyBody = <String, TextStyle>{
  'black': TextStyle(
    fontSize: 16,
    fontWeight: FontWeight.w900,
    height: 1.5,
    fontFamily: 'Inter',
  ),
  'extraBold': TextStyle(
    fontSize: 16,
    fontWeight: FontWeight.w800,
    height: 1.5,
    fontFamily: 'Inter',
  ),
  'bold': TextStyle(
    fontSize: 16,
    fontWeight: FontWeight.w700,
    height: 1.5,
    fontFamily: 'Inter',
  ),
  'semiBold': TextStyle(
    fontSize: 16,
    fontWeight: FontWeight.w600,
    height: 1.5,
    fontFamily: 'Inter',
  ),
  'medium': TextStyle(
    fontSize: 14,
    fontWeight: FontWeight.w500,
    height: 1.5,
    fontFamily: 'Inter',
  ),
  'regular': TextStyle(
    fontSize: 16,
    fontWeight: FontWeight.w400,
    height: 1.5,
    fontFamily: 'Inter',
  ),
  'light': TextStyle(
    fontSize: 16,
    fontWeight: FontWeight.w300,
    height: 1.5,
    fontFamily: 'Inter',
  ),
  'extraLight': TextStyle(
    fontSize: 16,
    fontWeight: FontWeight.w200,
    height: 1.5,
    fontFamily: 'Inter',
  ),
  'thin': TextStyle(
    fontSize: 16,
    fontWeight: FontWeight.w100,
    height: 1.5,
    fontFamily: 'Inter',
  ),
};

const Map<String, TextStyle> _darkTypographyCaption = <String, TextStyle>{
  'black': TextStyle(
    fontSize: 12,
    fontWeight: FontWeight.w900,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'extraBold': TextStyle(
    fontSize: 12,
    fontWeight: FontWeight.w800,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'bold': TextStyle(
    fontSize: 12,
    fontWeight: FontWeight.w700,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'semiBold': TextStyle(
    fontSize: 12,
    fontWeight: FontWeight.w600,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'medium': TextStyle(
    fontSize: 12,
    fontWeight: FontWeight.w500,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'regular': TextStyle(
    fontSize: 12,
    fontWeight: FontWeight.w400,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'light': TextStyle(
    fontSize: 12,
    fontWeight: FontWeight.w300,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'extraLight': TextStyle(
    fontSize: 12,
    fontWeight: FontWeight.w200,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'thin': TextStyle(
    fontSize: 12,
    fontWeight: FontWeight.w100,
    height: 1.4,
    fontFamily: 'Inter',
  ),
};

const Map<String, TextStyle> _darkTypographyDisplay = <String, TextStyle>{
  'black': TextStyle(
    fontSize: 32,
    fontWeight: FontWeight.w900,
    height: 1.2,
    fontFamily: 'Inter',
  ),
  'extraBold': TextStyle(
    fontSize: 32,
    fontWeight: FontWeight.w800,
    height: 1.2,
    fontFamily: 'Inter',
  ),
  'bold': TextStyle(
    fontSize: 32,
    fontWeight: FontWeight.w700,
    height: 1.2,
    fontFamily: 'Inter',
  ),
  'semiBold': TextStyle(
    fontSize: 32,
    fontWeight: FontWeight.w600,
    height: 1.2,
    fontFamily: 'Inter',
  ),
  'medium': TextStyle(
    fontSize: 32,
    fontWeight: FontWeight.w500,
    height: 1.2,
    fontFamily: 'Inter',
  ),
  'regular': TextStyle(
    fontSize: 32,
    fontWeight: FontWeight.w400,
    height: 1.2,
    fontFamily: 'Inter',
  ),
  'light': TextStyle(
    fontSize: 32,
    fontWeight: FontWeight.w300,
    height: 1.2,
    fontFamily: 'Inter',
  ),
  'extraLight': TextStyle(
    fontSize: 32,
    fontWeight: FontWeight.w200,
    height: 1.2,
    fontFamily: 'Inter',
  ),
  'thin': TextStyle(
    fontSize: 32,
    fontWeight: FontWeight.w100,
    height: 1.2,
    fontFamily: 'Inter',
  ),
};

const Map<String, TextStyle> _darkTypographyHeadline = <String, TextStyle>{
  'black': TextStyle(
    fontSize: 28,
    fontWeight: FontWeight.w900,
    height: 1.3,
    fontFamily: 'Inter',
  ),
  'extraBold': TextStyle(
    fontSize: 28,
    fontWeight: FontWeight.w800,
    height: 1.3,
    fontFamily: 'Inter',
  ),
  'bold': TextStyle(
    fontSize: 28,
    fontWeight: FontWeight.w700,
    height: 1.3,
    fontFamily: 'Inter',
  ),
  'semiBold': TextStyle(
    fontSize: 28,
    fontWeight: FontWeight.w600,
    height: 1.3,
    fontFamily: 'Inter',
  ),
  'medium': TextStyle(
    fontSize: 28,
    fontWeight: FontWeight.w500,
    height: 1.3,
    fontFamily: 'Inter',
  ),
  'regular': TextStyle(
    fontSize: 28,
    fontWeight: FontWeight.w400,
    height: 1.3,
    fontFamily: 'Inter',
  ),
  'light': TextStyle(
    fontSize: 28,
    fontWeight: FontWeight.w300,
    height: 1.3,
    fontFamily: 'Inter',
  ),
  'extraLight': TextStyle(
    fontSize: 28,
    fontWeight: FontWeight.w200,
    height: 1.3,
    fontFamily: 'Inter',
  ),
  'thin': TextStyle(
    fontSize: 28,
    fontWeight: FontWeight.w100,
    height: 1.3,
    fontFamily: 'Inter',
  ),
};

const Map<String, TextStyle> _darkTypographyLabel = <String, TextStyle>{
  'black': TextStyle(
    fontSize: 14,
    fontWeight: FontWeight.w900,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'extraBold': TextStyle(
    fontSize: 14,
    fontWeight: FontWeight.w800,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'bold': TextStyle(
    fontSize: 14,
    fontWeight: FontWeight.w700,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'semiBold': TextStyle(
    fontSize: 14,
    fontWeight: FontWeight.w600,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'medium': TextStyle(
    fontSize: 12,
    fontWeight: FontWeight.w500,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'regular': TextStyle(
    fontSize: 14,
    fontWeight: FontWeight.w400,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'light': TextStyle(
    fontSize: 14,
    fontWeight: FontWeight.w300,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'extraLight': TextStyle(
    fontSize: 14,
    fontWeight: FontWeight.w200,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'thin': TextStyle(
    fontSize: 14,
    fontWeight: FontWeight.w100,
    height: 1.4,
    fontFamily: 'Inter',
  ),
};

const Map<String, TextStyle> _darkTypographyTitle = <String, TextStyle>{
  'black': TextStyle(
    fontSize: 20,
    fontWeight: FontWeight.w900,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'extraBold': TextStyle(
    fontSize: 20,
    fontWeight: FontWeight.w800,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'bold': TextStyle(
    fontSize: 20,
    fontWeight: FontWeight.w700,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'semiBold': TextStyle(
    fontSize: 20,
    fontWeight: FontWeight.w600,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'medium': TextStyle(
    fontSize: 16,
    fontWeight: FontWeight.w500,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'regular': TextStyle(
    fontSize: 20,
    fontWeight: FontWeight.w400,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'light': TextStyle(
    fontSize: 20,
    fontWeight: FontWeight.w300,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'extraLight': TextStyle(
    fontSize: 20,
    fontWeight: FontWeight.w200,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'thin': TextStyle(
    fontSize: 20,
    fontWeight: FontWeight.w100,
    height: 1.4,
    fontFamily: 'Inter',
  ),
};

const Map<String, Color> _lightColorAction = <String, Color>{
  'filledPrimary': Color(0xFF1A1A2E),
  'filledHover': Color(0xFF2D3A8C),
  'ghostPrimary': Color(0xFFE94560),
  'ghostHover': Color(0xFFFF6B7A),
  'outline': Color(0xFF1A1A2E),
  'disabled': Color(0xFFE5E7EB),
  'filledDanger': Color(0xFFEF4444),
};

const Map<String, Color> _lightColorBrand = <String, Color>{
  'primary': Color(0xFF1A1A2E),
  'container': Color(0xFFF8F9FA),
};

const Map<String, Color> _lightColorCanvas = <String, Color>{
  'primary': Color(0xFFF8F9FA),
  'secondary': Color(0xFFF3F4F6),
  'tertiary': Color(0xFFE5E7EB),
  'error': Color(0xFFFEF2F2),
  'info': Color(0xFFEFF6FF),
  'warning': Color(0xFFFFFBEB),
  'success': Color(0xFFECFDF5),
  'neutral': Color(0xFFF3F4F6),
  'brand': Color(0xFF1A1A2E),
};

const Map<String, Color> _lightColorFeedback = <String, Color>{
  'warning': Color(0xFFFFA500),
  'danger': Color(0xFFEF4444),
  'success': Color(0xFF10B981),
  'info': Color(0xFF4A90E2),
};

const Map<String, Color> _lightColorForeground = <String, Color>{
  'primary': Color(0xFF1A1A2E),
  'subtle': Color(0xFF4A4A5A),
  'title': Color(0xFF1A1A2E),
  'body': Color(0xFF6B6B7B),
  'disabled': Color(0xFF9CA3AF),
  'placeholder': Color(0xFF9CA3AF),
  'inverse': Color(0xFFFFFFFF),
  'success': Color(0xFF10B981),
  'info': Color(0xFF4A90E2),
  'warning': Color(0xFFFFA500),
  'error': Color(0xFFEF4444),
};

const Map<String, Color> _lightColorIcon = <String, Color>{
  'primary': Color(0xFF1A1A2E),
  'subtle': Color(0xFFE94560),
  'title': Color(0xFF1A1A2E),
  'body': Color(0xFF6B6B7B),
  'disabled': Color(0xFF9CA3AF),
  'inverse': Color(0xFFFFFFFF),
  'success': Color(0xFF10B981),
  'info': Color(0xFF4A90E2),
  'warning': Color(0xFFFFA500),
  'error': Color(0xFFEF4444),
};

const Map<String, Color> _lightColorIndicator = <String, Color>{
  'urgent': Color(0xFFEF4444),
  'pending': Color(0xFFFFA500),
  'inReview': Color(0xFF4A90E2),
  'interview': Color(0xFF9B59B6),
  'offer': Color(0xFF10B981),
  'hired': Color(0xFF10B981),
  'rejected': Color(0xFFEF4444),
};

const Map<String, Color> _lightColorInput = <String, Color>{
  'primary': Color(0xFF1A1A2E),
  'label': Color(0xFF4A4A5A),
  'value': Color(0xFF1A1A2E),
  'placeholder': Color(0xFF9CA3AF),
  'disabled': Color(0xFF9CA3AF),
  'fill': Color(0xFFFFFFFF),
  'outline': Color(0xFFE5E7EB),
  'focus': Color(0xFF1A1A2E),
  'error': Color(0xFFEF4444),
};

const Map<String, Color> _lightColorStroke = <String, Color>{
  'emphasis': Color(0xFF1A1A2E),
  'primary': Color(0xFFE5E7EB),
  'divider': Color(0xFFE5E7EB),
  'inverse': Color(0xFFFFFFFF),
  'error': Color(0xFFEF4444),
};

const Map<String, Color> _lightColorSurface = <String, Color>{
  'card': Color(0xFFFFFFFF),
};

const Map<String, double> _lightSizeBlur = <String, double>{
  'xs': 2.0,
  'sm': 4.0,
  'md': 8.0,
  'lg': 16.0,
  'xl': 24.0,
};

const Map<String, double> _lightSizeFont = <String, double>{
  'xs': 10.0,
  'sm': 12.0,
  'md': 14.0,
  'lg': 16.0,
  'xl': 20.0,
  'x2l': 24.0,
  'x3l': 32.0,
};

const Map<String, double> _lightSizeIcon = <String, double>{
  'xs': 12.0,
  'sm': 16.0,
  'md': 20.0,
  'lg': 24.0,
  'xl': 32.0,
  'x2l': 40.0,
  'x3l': 48.0,
};

const Map<String, double> _lightSizeMotion = <String, double>{
  'xs': 50.0,
  'sm': 100.0,
  'md': 200.0,
  'lg': 300.0,
  'xl': 500.0,
};

const Map<String, double> _lightSizePadding = <String, double>{
  'xs': 4.0,
  'sm': 8.0,
  'md': 12.0,
  'lg': 16.0,
  'xl': 20.0,
  'x2l': 24.0,
  'x3l': 32.0,
  'x4l': 40.0,
  'x5l': 48.0,
  'x6l': 64.0,
  'x7l': 80.0,
};

const Map<String, double> _lightSizeRadius = <String, double>{
  'xs': 4.0,
  'sm': 6.0,
  'md': 8.0,
  'lg': 12.0,
  'xl': 16.0,
  'x2l': 20.0,
  'x3l': 24.0,
  'x4l': 32.0,
  'pill': 9999.0,
};

const Map<String, double> _lightSizeSpacing = <String, double>{
  'xs': 4.0,
  'sm': 8.0,
  'md': 12.0,
  'lg': 16.0,
  'xl': 20.0,
  'x2l': 24.0,
  'x3l': 32.0,
  'x4l': 40.0,
  'x5l': 48.0,
  'x6l': 64.0,
  'x7l': 80.0,
};

const Map<String, TextStyle> _lightTypographyBody = <String, TextStyle>{
  'black': TextStyle(
    fontSize: 16,
    fontWeight: FontWeight.w900,
    height: 1.5,
    fontFamily: 'Inter',
  ),
  'extraBold': TextStyle(
    fontSize: 16,
    fontWeight: FontWeight.w800,
    height: 1.5,
    fontFamily: 'Inter',
  ),
  'bold': TextStyle(
    fontSize: 16,
    fontWeight: FontWeight.w700,
    height: 1.5,
    fontFamily: 'Inter',
  ),
  'semiBold': TextStyle(
    fontSize: 16,
    fontWeight: FontWeight.w600,
    height: 1.5,
    fontFamily: 'Inter',
  ),
  'medium': TextStyle(
    fontSize: 14,
    fontWeight: FontWeight.w500,
    height: 1.5,
    fontFamily: 'Inter',
  ),
  'regular': TextStyle(
    fontSize: 16,
    fontWeight: FontWeight.w400,
    height: 1.5,
    fontFamily: 'Inter',
  ),
  'light': TextStyle(
    fontSize: 16,
    fontWeight: FontWeight.w300,
    height: 1.5,
    fontFamily: 'Inter',
  ),
  'extraLight': TextStyle(
    fontSize: 16,
    fontWeight: FontWeight.w200,
    height: 1.5,
    fontFamily: 'Inter',
  ),
  'thin': TextStyle(
    fontSize: 16,
    fontWeight: FontWeight.w100,
    height: 1.5,
    fontFamily: 'Inter',
  ),
};

const Map<String, TextStyle> _lightTypographyCaption = <String, TextStyle>{
  'black': TextStyle(
    fontSize: 12,
    fontWeight: FontWeight.w900,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'extraBold': TextStyle(
    fontSize: 12,
    fontWeight: FontWeight.w800,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'bold': TextStyle(
    fontSize: 12,
    fontWeight: FontWeight.w700,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'semiBold': TextStyle(
    fontSize: 12,
    fontWeight: FontWeight.w600,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'medium': TextStyle(
    fontSize: 12,
    fontWeight: FontWeight.w500,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'regular': TextStyle(
    fontSize: 12,
    fontWeight: FontWeight.w400,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'light': TextStyle(
    fontSize: 12,
    fontWeight: FontWeight.w300,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'extraLight': TextStyle(
    fontSize: 12,
    fontWeight: FontWeight.w200,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'thin': TextStyle(
    fontSize: 12,
    fontWeight: FontWeight.w100,
    height: 1.4,
    fontFamily: 'Inter',
  ),
};

const Map<String, TextStyle> _lightTypographyDisplay = <String, TextStyle>{
  'black': TextStyle(
    fontSize: 32,
    fontWeight: FontWeight.w900,
    height: 1.2,
    fontFamily: 'Inter',
  ),
  'extraBold': TextStyle(
    fontSize: 32,
    fontWeight: FontWeight.w800,
    height: 1.2,
    fontFamily: 'Inter',
  ),
  'bold': TextStyle(
    fontSize: 32,
    fontWeight: FontWeight.w700,
    height: 1.2,
    fontFamily: 'Inter',
  ),
  'semiBold': TextStyle(
    fontSize: 32,
    fontWeight: FontWeight.w600,
    height: 1.2,
    fontFamily: 'Inter',
  ),
  'medium': TextStyle(
    fontSize: 32,
    fontWeight: FontWeight.w500,
    height: 1.2,
    fontFamily: 'Inter',
  ),
  'regular': TextStyle(
    fontSize: 32,
    fontWeight: FontWeight.w400,
    height: 1.2,
    fontFamily: 'Inter',
  ),
  'light': TextStyle(
    fontSize: 32,
    fontWeight: FontWeight.w300,
    height: 1.2,
    fontFamily: 'Inter',
  ),
  'extraLight': TextStyle(
    fontSize: 32,
    fontWeight: FontWeight.w200,
    height: 1.2,
    fontFamily: 'Inter',
  ),
  'thin': TextStyle(
    fontSize: 32,
    fontWeight: FontWeight.w100,
    height: 1.2,
    fontFamily: 'Inter',
  ),
};

const Map<String, TextStyle> _lightTypographyHeadline = <String, TextStyle>{
  'black': TextStyle(
    fontSize: 28,
    fontWeight: FontWeight.w900,
    height: 1.3,
    fontFamily: 'Inter',
  ),
  'extraBold': TextStyle(
    fontSize: 28,
    fontWeight: FontWeight.w800,
    height: 1.3,
    fontFamily: 'Inter',
  ),
  'bold': TextStyle(
    fontSize: 28,
    fontWeight: FontWeight.w700,
    height: 1.3,
    fontFamily: 'Inter',
  ),
  'semiBold': TextStyle(
    fontSize: 28,
    fontWeight: FontWeight.w600,
    height: 1.3,
    fontFamily: 'Inter',
  ),
  'medium': TextStyle(
    fontSize: 28,
    fontWeight: FontWeight.w500,
    height: 1.3,
    fontFamily: 'Inter',
  ),
  'regular': TextStyle(
    fontSize: 28,
    fontWeight: FontWeight.w400,
    height: 1.3,
    fontFamily: 'Inter',
  ),
  'light': TextStyle(
    fontSize: 28,
    fontWeight: FontWeight.w300,
    height: 1.3,
    fontFamily: 'Inter',
  ),
  'extraLight': TextStyle(
    fontSize: 28,
    fontWeight: FontWeight.w200,
    height: 1.3,
    fontFamily: 'Inter',
  ),
  'thin': TextStyle(
    fontSize: 28,
    fontWeight: FontWeight.w100,
    height: 1.3,
    fontFamily: 'Inter',
  ),
};

const Map<String, TextStyle> _lightTypographyLabel = <String, TextStyle>{
  'black': TextStyle(
    fontSize: 14,
    fontWeight: FontWeight.w900,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'extraBold': TextStyle(
    fontSize: 14,
    fontWeight: FontWeight.w800,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'bold': TextStyle(
    fontSize: 14,
    fontWeight: FontWeight.w700,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'semiBold': TextStyle(
    fontSize: 14,
    fontWeight: FontWeight.w600,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'medium': TextStyle(
    fontSize: 12,
    fontWeight: FontWeight.w500,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'regular': TextStyle(
    fontSize: 14,
    fontWeight: FontWeight.w400,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'light': TextStyle(
    fontSize: 14,
    fontWeight: FontWeight.w300,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'extraLight': TextStyle(
    fontSize: 14,
    fontWeight: FontWeight.w200,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'thin': TextStyle(
    fontSize: 14,
    fontWeight: FontWeight.w100,
    height: 1.4,
    fontFamily: 'Inter',
  ),
};

const Map<String, TextStyle> _lightTypographyTitle = <String, TextStyle>{
  'black': TextStyle(
    fontSize: 20,
    fontWeight: FontWeight.w900,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'extraBold': TextStyle(
    fontSize: 20,
    fontWeight: FontWeight.w800,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'bold': TextStyle(
    fontSize: 20,
    fontWeight: FontWeight.w700,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'semiBold': TextStyle(
    fontSize: 20,
    fontWeight: FontWeight.w600,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'medium': TextStyle(
    fontSize: 16,
    fontWeight: FontWeight.w500,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'regular': TextStyle(
    fontSize: 20,
    fontWeight: FontWeight.w400,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'light': TextStyle(
    fontSize: 20,
    fontWeight: FontWeight.w300,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'extraLight': TextStyle(
    fontSize: 20,
    fontWeight: FontWeight.w200,
    height: 1.4,
    fontFamily: 'Inter',
  ),
  'thin': TextStyle(
    fontSize: 20,
    fontWeight: FontWeight.w100,
    height: 1.4,
    fontFamily: 'Inter',
  ),
};
